
export const appTexts: Record<string, any> = {
  ar: {
    appTitle: "المفتش الذكي",
    appDescription: "تطبيق تدبير أنشطة المفتش التربوي",
    // Inspector Modal
    inspectorModal_title: "بيانات المفتش",
    inspectorModal_fullName: "الإسم الكامل",
    inspectorModal_financialId: "رقم التأجير",
    inspectorModal_financialIdPlaceholder: "رقم التأجير...",
    inspectorModal_regionalDirectorTitle: "صفة المسؤول الإقليمي",
    inspectorModal_regionalDirectorTitlePlaceholder: "مثال: المدير الإقليمي أو المكلف بتدبير المديرية",
    inspectorModal_framework: "الإطار",
    inspectorModal_selectFramework: "اختر الإطار",
    inspectorModal_academy: "الأكاديمية الجهوية",
    inspectorModal_directorate: "المديرية الإقليمية",
    inspectorModal_subject: "التخصص",
    inspectorModal_subjectPlaceholder: "مثلا: التربية البدنية والرياضية",
    inspectorModal_securityTitle: "الأمان",
    inspectorModal_newPassword: "كلمة المرور الجديدة",
    inspectorModal_confirmPassword: "تأكيد كلمة المرور",
    inspectorModal_passwordPlaceholder: "اتركها فارغة إذا لم ترد التغيير",
    inspectorModal_passwordMismatch: "كلمات المرور غير متطابقة",
    framework_inspector_primary: "مفتش التعليم الإبتدائي",
    framework_inspector_middle: "مفتش التعليم الثانوي الإعدادي",
    framework_inspector_high: "مفتش التعليم الثانوي التأهيلي",
    select_academy: "اختر الأكاديمية",
    select_directorate: "اختر المديرية",
    language: "اللغة",
    save: "حفظ",
    delete: "حذف",
    cancel: "إلغاء",
    inspectorModal_cancelBtn: "إلغاء",
    all: "الكل",
    confirmDelete: "تأكيد",
    clear: "مسح",
    alert_fill_required: "المرجو ملء الحقول الإجبارية",
    evaluation_subject: "المادة",
    search: "بحث",
    "Inspections": "التفتيشات",
    "Visites": "الزيارات",
    "Service des Affaires Pédagogiques": "مصلحة الشؤون التربوية",
    "أنشطة أخرى - رياضة مدرسية": "أنشطة أخرى - رياضة مدرسية",
    "أنشطة أخرى - المصادقة على التوزيع الحلقي": "أنشطة أخرى - المصادقة على التوزيع الحلقي",
    "درس تجريبي": "درس تجريبي",
    "الدروس التجريبية": "الدروس التجريبية",
    "أنشطة أخرى - مراسلة": "أنشطة أخرى - مراسلة",
    "أنشطة أخرى - المصادقة على جداول الحصص": "أنشطة أخرى - المصادقة على جداول الحصص",
    "أنشطة أخرى - تقرير إداري": "أنشطة أخرى - تقرير إداري",
    "أنشطة أخرى - امتحانات الباكالوريا": "أنشطة أخرى - امتحانات الباكالوريا",
    "الندوات واللقاءات التربوية": "الندوات واللقاءات التربوية",
    
    // Home
    home_pageTitle: "الرئيسية",
    home_inspectorCardTitle: "المفتش",
    home_inspectorCardDesc: "تعديل البيانات الشخصية والإدارية",
    home_teachersCardTitle: "هيئة التدريس",
    home_teachersCardDesc: "تدبير ملفات الأساتذة والزيارات",
    home_inspectionSpaceCardTitle: "فضاء التفتيش",
    home_reportsCardTitle: "تقارير التفتيش ",
    home_reportsCardDesc: "الاطلاع على تقارير التفتيش والزيارات",
    home_otherReportsCardTitle: "تقارير أخرى",
    home_otherReportsCardDesc: "المراسلات والتقارير الإدارية",
    home_transmissionSlipCardTitle: "ورقة الارسال",
    home_transmissionSlipCardDesc: "وثيقة ضبط المراسلات الإدارية ",
    home_activitySummaryCardTitle: "البرنامج والحصيلة",
    home_activitySummaryCardDesc: "الحصيلة الدورية والسنوية للأنشطة والبرنامج",
    home_settingsCardTitle: "الإعدادات",
    home_statisticsCardTitle: "الإحصائيات",
    home_statisticsCardDesc: "مؤشرات ورسوم بيانية حول الأداء",
    home_researchCardTitle: "البحث التربوي",
    home_researchCardDesc: "موجه منهجي لإعداد البحوث التربوية",
    
    // Teachers List
    teachersList_pageTitle: "لائحة الأساتذة",
    teachersList_selectTitle: "اختيار أستاذ",
    teachersList_addTeacher: "إضافة أستاذ",
    teachersList_searchLabel: "بحث",
    sidebar_inspectorWindow: "نافذة المفتش",
    sidebar_inspectorWindowDesc: "تعديل بيانات المفتش",
    sidebar_appVersion: "المفتش الذكي اصدار 1.1",
    sidebar_localBackup: "نسخ احتياطي محلي",
    sidebar_localRestore: "استعادة محلية",
    sidebar_cloudBackup: "نسخ احتياطي سحابي",
    sidebar_cloudRestore: "استعادة سحابية",
    teachersList_searchPlaceholder: "بحث بالإسم أو المؤسسة...",
    teachersList_selectAlertTitle: "تنبيه",
    teachersList_selectAlertText: "المرجو اختيار أستاذ من اللائحة",
    teachersList_addTeachersFirst: "المرجو إضافة أساتذة أولاً",
    teachersList_colFullName: "الإسم الكامل",
    teachersList_colInstitution: "المؤسسة",
    teachersList_colFramework: "الإطار",
    teachersList_colLastScore: "آخر نقطة",
    teachersList_colActions: "إجراءات",
    teachersList_noResults: "لا توجد نتائج",
    select: "اختيار",
    viewDetails: "التفاصيل",
    edit: "تعديل",
    importFromExcel: "استيراد من Excel",
    importHelp_title: "تعليمات الاستيراد",
    teachersList_exportTitle: "تصدير لائحة الأساتذة",
    teachersList_exportBtn: "تصدير اللائحة",
    settings_platformConfigTitle: "مزامنة الأساتذة (Firebase)",
    settings_platformConfigHelp: "استخدم هذا الخيار لمزامنة لائحة الأساتذة من قاعدة البيانات المركزية (Firebase).",
    importHelp_intro: "يجب أن يحتوي ملف Excel على الأعمدة التالية (يدعم التطبيق العناوين بالعربية أو بالفرنسية/الإنجليزية):",
    importHelp_col1: "<b>fullName</b>: الإسم الكامل",
    importHelp_col2: "<b>employeeId</b>: رقم التأجير",
    importHelp_col3: "<b>genre</b>: الجنس (ذكر/أنثى)",
    importHelp_col4: "<b>framework</b>: الإطار",
    importHelp_col5: "<b>institution</b>: المؤسسة",
    importHelp_col6: "<b>subject</b>: المادة",
    importHelp_col7: "<b>grade</b>: الدرجة",
    importHelp_col8: "<b>rank</b>: الرتبة",
    importHelp_col9: "<b>lastInspectionScore</b>: آخر نقطة تفتيش",
    importHelp_col10: "<b>lastInspectionDate</b>: تاريخ آخر تفتيش (YYYY-MM-DD)",
    importHelp_col11: "<b>lastInspector</b>: إسم المفتش السابق",
    importHelp_col12: "<b>image</b>: رابط الصورة (اختياري)",
    importHelp_col13: "<b>promotionPace</b>: نسق الترقية (rapid/medium/slow)",
    importHelp_button_proceed: "متابعة للاستيراد",
    errorImportInvalidFormat: "صيغة الملف غير صحيحة",
    errorImport: "حدث خطأ أثناء الاستيراد",
    
    // Teacher Detail
    teacherDetail_pageTitle: "ملف الأستاذ",
    teacherDetail_addVisit: "إضافة زيارة",
    teacherDetail_addInspection: "إضافة تفتيش",
    teacherDetail_infoCardTitle: "المعلومات المهنية",
    teacherDetail_historyCardTitle: "سجل الزيارات والتفتيشات",
    teacherDetail_noReports: "لا توجد تقارير مسجلة",
    teacher_female: "الأستاذة",
    teacher_male: "الأستاذ",
    teacher_fullName: "الإسم الكامل",
    teacher_subject: "المادة",
    teacher_lastScore: "آخر نقطة",
    teacher_employeeId: "رقم التأجير",
    teacher_grade: "الدرجة",
    teacher_lastDate: "تاريخ آخر تفتيش",
    teacher_framework: "الإطار",
    teacher_rank: "الرتبة",
    teacher_lastInspector: "المفتش",
    teacher_institution: "المؤسسة",
    teacher_genre: "الجنس",
    teacher_recruitmentDate: "تاريخ التوظيف",
    teacher_tenureDate: "تاريخ الترسيم",
    teacher_gradeDate: "تاريخ الدرجة",
    teacher_rankDate: "تاريخ الرتبة",
    genre_male: "ذكر",
    genre_female: "أنثى",
    back: "رجوع",
    home: "الرئيسية",
    visit: "زيارة",
    inspection: "تفتيش",
    reportDatePrefix: "التاريخ",
    reportHasLessonPlan: "مرفق بصورة الجذاذة",
    viewExport: "معاينة / تصدير",
    sector_label: "القطاع",
    sector_public: "عمومي",
    sector_private: "خصوصي",
    
    // Add Teacher Modal
    addTeacherModal_addTitle: "إضافة أستاذ جديد",
    addTeacherModal_editTitle: "تعديل بيانات الأستاذ",
    addTeacherModal_saveTeacher: "إضافة الأستاذ",
    addTeacherModal_saveChanges: "حفظ التغييرات",
    addTeacherModal_fillAllFields: "المرجو ملء جميع الحقول الضرورية",
    addTeacherModal_selectFramework: "اختر الإطار",
    addTeacherModal_selectSubject: "اختر المادة",
    addTeacherModal_selectGrade: "اختر الدرجة",
    addTeacherModal_lastInspectionTitle: "بيانات التفتيش السابق",
    framework_primary: "أستاذ التعليم الإبتدائي",
    framework_middle: "أستاذ التعليم الثانوي الإعدادي",
    framework_high: "أستاذ التعليم الثانوي التأهيلي",
    
    // Report Modal / Evaluation
    reportModal_lessonObservation: "ملاحظات حول سير الدرس",
    evaluation_field_tools: "الوسائل التعليمية",
    evaluation_field_studentCount: "عدد التلاميذ",
    evaluation_field_class: "القسم",
    evaluation_field_level: "المستوى",
    evaluation_field_activity: "النشاط",
    evaluation_field_activityCategory: "نوع النشاط",
    evaluation_field_lessonGoal: "هدف الحصة",
    evaluation_criterion: "معيار",
    reportModal_criteria: "المعايير والمؤشرات",
    report_dateLabel: "حرر بتاريخ",
    report_awardedScore: "النقطة الممنوحة",
    signature_title_1: "توقيع المفتش",
    signature_regionalDirector: "توقيع {regionalDirectorTitle}",
    signature_institutionDirector: "توقيع مدير المؤسسة",
    errorPopupBlocker: "تم حظر النافذة المنبثقة. المرجو السماح بالنوافذ المنبثقة للطباعة.",
    errorExportLibrary: "مكتبات التصدير غير متوفرة",
    close: "إغلاق",
    share: "مشاركة",
    exportWord: "Word تصدير",
    exportPdf: "PDF تصدير",
    print: "طباعة",
    inspectionReport: "تقرير تفتيش",
    visitReport: "تقرير زيارة صفية",
    ministryLogoAlt: "شعار الوزارة",
    "المدير الإقليمي": "المدير الإقليمي",
    "Directeur Provincial": "المدير الإقليمي",
    regionalAcademyLabel: "الأكاديمية الجهوية:",
    regionalDirectorateLabel: "المديرية الإقليمية:",
    department_pedagogicalAffairs: "مصلحة الشؤون التربوية والخريطة المدرسية",
    
    // Sport Activities and Categories
    "الارجاع الكروي": "الارجاع الكروي",
    "ألعاب القوى": "ألعاب القوى",
    "الجمباز": "الجمباز",
    "الرقابة والتحرر": "الرقابة والتحرر",
    "الكره الطائرة": "الكرة الطائرة",
    "الكرة الطائرة": "الكرة الطائرة",
    "كرة الريشة": "كرة الريشة",
    "التنس": "التنس",
    "كرة السلة": "كرة السلة",
    "كرة اليد": "كرة اليد",
    "كرة القدم": "كرة القدم",
    
    // Levels
    "الأولى إعدادي": "الأولى إعدادي",
    "الثانية إعدادي": "الثانية إعدادي",
    "الثالثة إعدادي": "الثالثة إعدادي",
    "الجذع مشترك": "الجذع مشترك",
    "الأولى بكالوريا": "الأولى بكالوريا",
    "الثانية بكالوريا": "الثانية بكالوريا",
    
    // Reports List
    reportsList_pageTitle: "أرشيف التقارير",
    reportsList_newReport: "تقرير جديد",
    reportsList_filterTitle: "تصفية",
    teacher: "الأستاذ",
    reportsList_allTeachers: "جميع الأساتذة",
    reportsList_reportType: "نوع التقرير",
    reportsList_allTypes: "الكل",
    reportsList_academicYear: "الموسم الدراسي",
    reportsList_allYears: "جميع المواسم",
    type: "النوع",
    date: "التاريخ",
    score: "النقطة",
    actions: "إجراءات",
    reportsList_noResults: "لا توجد تقارير",
    
    // Evaluation Page
    evaluation_scoreLabel: "النقطة المقترحة (على 20)",
    evaluation_scoreRequired: "المرجو إدخال النقطة",
    evaluation_generatingAI: "جاري توليد الملاحظات بالذكاء الاصطناعي...",
    evaluation_generateAIBtn: "توليد الملاحظات (AI)",
    evaluation_generateAIForCriterion: "تحرير بالذكاء الاصطناعي",
    evaluation_mustHaveOneCriterion: "يجب أن يبقى معيار واحد على الأقل",
    evaluation_fieldValuePlaceholder: "أدخل المحتوى...",
    reportModal_lessonPlanSectionTitle: "صورة الجذاذة (اختياري)",
    evaluation_changeLessonPlanImage: "تغيير الصورة",
    evaluation_removeLessonPlanImage: "حذف الصورة",
    evaluation_takePhoto: "التقاط صورة",
    evaluation_uploadImage: "تحميل صورة",
    evaluation_criterionNamePlaceholder: "إسم المعيار",
    evaluation_commentsPlaceholder: "ملاحظات حول {0}...",
    evaluation_addCriterion: "إضافة معيار",
    otherReportModal_title: "معاينة التقرير",
    settings_selectCategory: "اختر الصنف",
    settings_selectActivity: "اختر النشاط",
    evaluation_selectLevel: "اختر المستوى",
    exportExcel: "Excel تصدير",
    exportHtml: "HTML تصدير",
    reportModal_newScore: "النقطة الممنوحة",
    report: "تقرير",
    delivered: "تم التسليم",
    mark_as_delivered: "تحديد كمُسلّم",
    unnamedField: "غير معنون",
    reportTemplate_standard: 'التقرير الوصفي',
    reportTemplate_network: 'تقرير شبكة المفتشية',
    overallAssessment: 'التقدير الإجمالي',
    overallAssessmentPlaceholder: 'أدخل التقدير الإجمالي هنا...',
    achievementLevel_placeholder: 'مستوى الإنجاز',
    achievementLevel_1: 'غير متحكم فيه',
    achievementLevel_2: 'في طور التحكم',
    achievementLevel_3: 'متحكم فيه',
    achievementLevel_4: 'متحكم فيه بامتياز',
    evaluation_network_domains: "المجالات",
    evaluation_network_indicators: "المؤشرات",
    evaluation_network_achievementLevel: "مستوى الإنجاز",
    evaluation_network_observations: "الملاحظات والتوجيهات",
    evaluation_notEvaluated: "غير مقيم",
    reportCustomization_title: "تخصيص العرض",
    reportCustomization_fontFamily: "خط التقرير",
    reportCustomization_fontSize: "حجم الخط",
    reportCustomization_logoScale: "حجم الشعار (%)",
    reportCustomization_margins: "الهوامش (سم)",
    reportCustomization_marginTop: "علوي",
    reportCustomization_marginBottom: "سفلي",
    reportCustomization_marginSide: "جانبي",
    
    // Other Reports
    otherReports_pageTitle: "تقارير ومراسلات أخرى",
    otherReports_formTitle: "إعداد تقرير أو مراسلة",
    editReport: "تعديل التقرير",
    otherReports_documentNumber: "رقم الإرسال:",
    otherReports_department: "إلى السيد(ة)",
    otherReports_selectDepartment: "اختر الجهة المرسل إليها",
    otherReports_subject: "الموضوع",
    otherReports_subjectPlaceholder: "موضوع التقرير أو المراسلة...",
    otherReports_reference: "المرجع",
    otherReports_referencePlaceholder: "مرجع المراسلة (اختياري)...",
    otherReports_addReference: "إضافة مرجع",
    otherReports_includeListInReport: "إدراج اللائحة في التقرير",
    otherReports_autoSelectionShortcuts: "اختصارات المصادقة التلقائية (بناءً على تحليل الجداول):",
    otherReports_selectAllCleanSchedules: "تحديد جميع الجداول السليمة",
    otherReports_selectSchedulesWithNotes: "تحديد الجداول التي بها ملاحظات",
    allInstitutions: "كل المؤسسات",
    allFrameworks: "كل الأطر",
    activitySummary_inspectorTitle: "حصيلة أنشطة المفتش التربوي",
    otherReports_contentPlaceholder: "اكتب رؤوس أقلام أو مسودة المحتوى هنا ليقوم الذكاء الاصطناعي بصياغتها...",
    otherReports_content: "المحتوى",
    otherReports_invitedTeachersTitle: "الأساتذة المعنيون / المدعوون",
    otherReports_searchTeacher: "بحث عن أستاذ...",
    otherReports_selectAll: "تحديد الكل",
    saveChanges: "حفظ التغييرات",
    otherReports_rephraseError: "خطأ في الصياغة",
    view: "معاينة",
    report_reference_field: "المرجع:",
    report_from: "من السيد:",
    report_framework_label: "الإطار:",
    report_subject_label: "التخصص:",
    report_to: "إلى:",
    report_subject_field: "الموضوع:",
    report_signature_line: "والسلام",
    otherReports_invitedListTitle: "لائحة الأساتذة",
    otherReport_blankTemplate: "تقرير فارغ",
    otherReport_selectTemplate: "اختيار نموذج",
    
    // Transmission Slip
    transmissionSlip_pageTitle: "جدول الإرسال",
    academicYear: "الموسم الدراسي",
    allYears: "جميع المواسم",
    allTypes: "جميع الأنواع",
    transmissionSlip_createTitle: "إعداد جدول إرسال جديد",
    transmissionSlip_editTitle: "تعديل جدول الإرسال",
    slip_slipNumber: "رقم الإرسال",
    transmissionSlip_slipNumberPlaceholder: "مثلاً: 12/2023",
    transmissionSlip_attachedReports: "الوثائق المرفقة",
    transmissionSlip_noReportsAdded: "لم يتم إضافة أي وثائق بعد",
    slip_item_copies: "عدد النسخ",
    slip_item_notes: "ملاحظات",
    transmissionSlip_addActivities: "إضافة تقارير من الأرشيف",
    transmissionSlip_savedSlips: "جداول الإرسال المحفوظة",
    transmissionSlip_noSavedSlips: "لا توجد جداول إرسال محفوظة",
    transmissionSlip_fillAllFields: "المرجو ملء جميع الحقول واختيار وثيقة واحدة على الأقل",
    cancelEdit: "إلغاء التعديل",
    selectActivities_title: "اختيار وثائق للإرسال",
    selectActivities_add: "إضافة ({0})",
    selectActivities_noReports: "لا توجد تقارير غير مرسلة",
    subject: "الموضوع",
    transmissionSlipModal_title: "معاينة جدول الإرسال",
    slip_item_seq: "ر.ت",
    slip_item_subject: "نوع الوثيقة وموضوعها",
    slip_activity_summary: "حصيلة الأنشطة",
    slip_notes_placeholder: "ملاحظات موحدة...",
    
    // Activity Summary
    activitySummary_pageTitle: "الحصيلة السنوية",
    activitySummary_reportType: "نوع النشاط",
    activitySummary_allTypes: "جميع الأنشطة",
    activitySummary_searchPlaceholder: "بحث في الموضوع...",
    activitySummary_noReports: "لا توجد أنشطة مسجلة في هذه الفترة.",
    activitySummary_type_visit: "زيارات",
    activitySummary_type_inspection: "تفتيشات",
    activitySummary_type_other: "أنشطة أخرى",
    activitySummary_type_experimentalLessons: "الدروس التجريبية",
    activitySummary_type_seminars: "الندوات واللقاءات التربوية",
    activitySummary_type_trainings: "التكوينات",
    activitySummary_type_sharedWork: "العمل المشترك",
    activitySummary_type_tenure: "الترسيم والكفاءة",
    activitySummary_card_program_title: "البرمجة",
    activitySummary_card_program_desc: "تخطيط وبرمجة الأنشطة والمهام",
    activitySummary_card_summary_title: "الحصيلة",
    activitySummary_card_summary_desc: "عرض إحصائيات وتقارير الأنشطة المنجزة",
    activitySummary_card_project_title: "المشروع",
    activitySummary_card_project_desc: "مشروع البرنامج العمل السنوي",
    activitySummary_zipping_title: "جاري تحضير الملفات...",
    activitySummary_zipping_desc1: "يتم الآن إنشاء ملف ZIP لجميع تقارير الموسم.",
    activitySummary_zipping_desc2: "يرجى الانتظار حتى اكتمال العملية.",
    
    // Activity Summary Periods
    activitySummary_choosePeriod: "اختيار فترة الحصيلة",
    activitySummary_semester: "الأسدس",
    activitySummary_semester1: "الأسدس الأول",
    activitySummary_semester2: "الأسدس الثاني",
    activitySummary_annual: "البرنامج والحصيلة",
    activitySummary_archiveTitle: "أرشيف المواسم الدراسية",
    activitySummary_startDate: "تاريخ البداية",
    activitySummary_endDate: "تاريخ النهاية",
    activitySummary_showReports: "عرض الحصيلة",
    activitySummary_changePeriod: "تغيير الفترة / الدورة",
    activitySummary_periodDateLabel: "عن الفترة الممتدة من {0} إلى {1}",
    
    // Inspection Space
    inspectionSpace_pedagogicalReports: "تقارير تربوية",
    inspectionSpace_title: "هيئة التدريس",
    inspectionSpace_button: "هيئة التدريس",
    inspectionSpace_exit: "خروج",
    inspectionSpace_chooseDay: "اختر اليوم",
    inspectionSpace_startTime: "ساعة البداية",
    inspectionSpace_duration: "المدة الزمنية",
    inspectionSpace_morning: "صباح",
    inspectionSpace_afternoon: "مساء",
    inspectionSpace_hour: "ساعة",
    inspectionSpace_hours: "ساعات",
    inspectionSpace_status_busy: "في حصة",
    inspectionSpace_status_free: "فارغ",
    inspectionSpace_status_onLeave: "رخصة",
    inspectionSpace_available: "متاح",
    inspectionSpace_busy: "مشغول",
    
    // Teacher Schedule Modal
    scheduleModal_title: "بطاقة معلومات الأستاذ",
    scheduleModal_tab_card: "بطاقة المعلومات",
    scheduleModal_tab_timetable: "جدول الحصص",
    scheduleModal_tab_licenses: "سجل الرخص",
    scheduleModal_totalWeeklyHours: "مجموع الساعات الأسبوعية:",
    scheduleModal_hour: "ساعة",
    scheduleModal_violationsTitle: "تنبيهات الضوابط التربوية",
    scheduleModal_noViolations: "لا توجد مخالفات مسجلة (المدة والراحة محترمة).",
    scheduleModal_assignmentsTitle: "جرد الحصص المسندة",
    scheduleModal_noAssignments: "لم يتم إدراج أسماء الأقسام في جدول الحصص بعد.",
    scheduleModal_scoreEvolution: "تطور النقطة:",
    scheduleModal_academicYears: "المواسم الدراسية",
    scheduleModal_reportsHistory: "سجل التقارير والزيارات",
    scheduleModal_noReports: "لا توجد تقارير مسجلة لهذا الأستاذ.",
    scheduleModal_scoreLabel: "النقطة:",
    violation_overTwoHours: "حصّة تتجاوز ساعتين",
    violation_lowWeeklyDuration: "الغلاف الزمني الأسبوعي أقل من ساعتين",
    violation_lowRestPeriod: "فترة راحة أقل من 44 ساعة",
    schedule_ass_label: "الجمعية الرياضية (ASS)",
    schedule_violation_label: "تنبيه (مخالفة الضوابط)",
    evaluation_previousInspectionData: "بيانات التفتيش السابق",
    evaluation_errorProofreading: "حدث خطأ أثناء التدقيق اللغوي",
    evaluation_noTextToProofread: "لا يوجد نص للتدقيق",
    evaluation_proofreadingAI: "جاري التدقيق اللغوي...",
    evaluation_proofreadAIBtn: "تدقيق لغوي (AI)",
    evaluation_academicSeasons: "المواسم الدراسية",
    evaluation_criteria_prep: "التخطيط والإعداد",
    evaluation_criteria_execution: "تدبير إنجاز الحصة",
    evaluation_criteria_evaluation: "التقويم",
    evaluation_criteria_professionalism: "التطور المهني والإلتزام",
    evaluation_analyticalReport: "تقرير تحليلي",
    inspection_report_title: "تقرير تفتيش تربوي",
    visit_report_title: "تقرير زيارة صفية",
    grade_label: "الدرجة",
    score_label: "النقطة",
    observation_progress: "ملاحظات حول سير الدرس",
    network_grid_c1: "الشروط المادية والتنظيمية",
    network_grid_c1_i1: "الوضعية المادية لفضاء التعلم",
    network_grid_c1_i2: "الوسائل التعليمية",
    network_grid_c1_i3: "تنظيم فضاء التعلم",
    network_grid_c2: "القدرة على التنظيم والتخطيط",
    network_grid_c2_i1: "وثائق تربوية محينة",
    network_grid_c2_i2: "احترام البرنامج الوطني لتدريس المادة",
    network_grid_c2_i3: "اجراء التقويم التشخيصي",
    network_grid_c2_i4: "وضوح الأهداف المسطرة للدرس",
    network_grid_c2_i5: "اختيار الوسائل التعليمية المناسبة",
    network_grid_c2_i6: "احترام الغلاف الزمني للحصة/للحلقة",
    network_grid_c2_i7: "اعتماد المشروع البيداغوجي والرياضي ومشروع الحلقة",
    network_grid_c3: "إنجاز الأعمال المرتبطة بالوظيفة",
    network_grid_c3_i1: "التمكن من مفاهيم ومصطلحات المادة المعرفية",
    network_grid_c3_i2: "التمكن من منهجية تدريس المادة",
    network_grid_c3_i3: "تماسك البناء الداخلي للدرس (التدرج والانسجام)",
    network_grid_c3_i4: "احترام توزيع زمن مكونات الحصة الدراسية",
    network_grid_c3_i5: "توظيف الوسائل التعليمية",
    network_grid_c3_i6: "مراعاة الفوارق الفردية بين المتعلمين والمتعلمات",
    network_grid_c3_i7: "ملاءمة أنشطة التقويم و/ أو الدعم لأهداف الدرس",
    network_grid_c4: "البحث والابتكار",
    network_grid_c4_i1: "اعتماد أساليب وطرق تدريس جديدة ومبتكرة",
    network_grid_c4_i2: "استخدام تكنولوجيا المعلومات والاتصال والموارد الرقمية",
    network_grid_c4_i3: "أنشطة البحث التربوي (فردية أو جماعية)",
    network_grid_c5: "المردودية",
    network_grid_c5_i1: "انخراط ومشاركة المتعلمين والمتعلمات",
    network_grid_c5_i2: "نشاط المتعلمين: استبصار- تفاعل- إنتاج- إنجاز- إبداع",
    network_grid_c5_i3: "نتائج التقويمات: تشخيصي- تكويني- إجمالي",
    network_grid_c5_i4: "المساهمة في تفعيل أنشطة الرياضة المدرسية",
    network_grid_c6: "السلوك المهني",
    network_grid_c6_i1: "التواصل المهني المؤسساتي",
    network_grid_c6_i2: "الجاذبية الشخصية: الحضور والهندام",
    network_grid_c6_i3: "الجانب العلائقي مع المتعلمين",
    network_level_0: "غير متوفر",
    network_level_1: "ينبغي الاشتغال عليه",
    network_level_2: "لا بأس به",
    network_level_3: "جيد",

    // Statistics
    statistics_pageTitle: "لوحة الإحصائيات",
    statistics_visits: "الزيارات",
    statistics_inspections: "التفتيشات",
    statistics_other: "تقارير أخرى",
    statistics_total: "المجموع العام",
    statistics_chartTitle: "تطور الأنشطة حسب الأشهر",
    statistics_distributionTitle: "توزيع الأنشطة",
    
    // Educational Research
    research_pageTitle: "البحث التربوي",
    research_labelTopic: "موضوع البحث المقترح:",
    research_placeholderTopic: "أدخل موضوع البحث التربوي...",
    research_generateButton: "توليد المقترح المنهجي",
    research_generating: "جاري إعداد الموجه...",
    research_section_problem: "الإشكالية المقترحة",
    research_section_hypothesis: "الفرضيات",
    research_section_methodology: "المنهجية والأدوات",
    research_section_plan: "تصميم البحث المقترح",
    research_helpText: "هذه النافذة تساعدك في بناء هيكلة أولية للبحث التربوي.",
    research_btn_instruments: "توليد نماذج الأدوات والمعايير",
    research_btn_refineMethodology: "تدقيق المنهجية",
    research_btn_fullFormulation: "صياغة البحث كليا وبالتفصيل",
    research_section_fullFormulation: "الصياغة الكلية والتفصيلية للبحث",
    research_downloadText: "تحميل النص",
    research_filename_prefix: "صياغة_بحث_",
    research_title_refineMethodology: "توليد تفاصيل أدق للمنهجية والأدوات",
    research_title_fullFormulation: "صياغة البحث كليا وبالتفصيل",
    research_title_instruments: "توليد نماذج تطبيقية للأدوات",

    // Settings
    settings_pageTitle: "الإعدادات",
    settings_tab_general: "عامة",
    settings_tab_reports: "التقارير",
    settings_fontSize: "التحكم في حجم الكتابة لكامل التطبيق",
    fontSize_reset: "إعادة تعيين",
    settings_ministryTitle: "ترويسة التقارير",
    settings_ministryDesc: "تخصيص الشعار والبيانات الإدارية",
    settings_ministryLogoLabel: "شعار الوزارة (بالعربية)",
    settings_ministryLogoFrLabel: "شعار الوزارة (بالفرنسية)",
    settings_changeLogo: "تغيير الشعار",
    settings_logoSpecs: "يفضل استخدام صورة PNG بخلفية شفافة",
    settings_logoHeight: "ارتفاع الشعار (AR)",
    settings_logoHeightFr: "ارتفاع الشعار (FR)",
    settings_aiConfig: "إعدادات الذكاء الاصطناعي",
    settings_geminiApiKey: "مفتاح API الخاص بـ Gemini",
    settings_geminiApiKeyHelp: "مطلوب لاستخدام ميزات الذكاء الاصطناعي في صياغة التقارير. يمكنك الحصول عليه مجاناً من Google AI Studio.",
    settings_getApiKey: "احصل على المفتاح من هنا",
    settings_syncFromCloudDesc: "تحديث التطبيق بآخر البيانات المحفوظة في السحابة:",
    settings_syncToCloudDesc: "حفظ بياناتك الحالية في السحابة (للمزامنة مع أجهزة أخرى):",
    settings_syncToCloudButton: "رفع إلى السحابة (حفظ)",
    settings_syncFromCloudButton: "تحديث من السحابة (جلب)",
    settings_syncFromCloudConfirmTitle: "تحديث من السحابة",
    settings_syncFromCloudConfirmMessage: "هل أنت متأكد أنك تريد جلب البيانات من السحابة؟ سيتم استبدال جميع بياناتك الحالية.",
    settings_academiesTitle: "الأكاديميات",
    settings_academiesDesc: "قائمة الأكاديميات الجهوية",
    settings_academyPlaceholder: "اسم الأكاديمية...",
    settings_addAcademy: "إضافة أكاديمية",
    settings_directoratesTitle: "المديريات",
    settings_directoratesDesc: "قائمة المديريات الإقليمية",
    settings_directoratePlaceholder: "اسم المديرية...",
    settings_addDirectorate: "إضافة مديرية",
    settings_departmentsTitle: "الأقسام والمصالح",
    settings_departmentsDesc: "الجهات المرسل إليها (رؤساء المصالح...)",
    settings_departmentPlaceholder: "اسم المصلحة...",
    settings_addDepartment: "إضافة مصلحة",
    settings_backupRestoreTitle: "النسخ الاحتياطي والاستعادة",
    settings_backupRestoreDesc: "حفظ البيانات محلياً أو استعادتها",
    settings_backupButton: "تحميل نسخة احتياطية",
    settings_restoreButton: "استعادة نسخة",
    settings_levelsTitle: "المستويات الدراسية",
    settings_levelsDesc: "المستويات المتاحة في التقارير",
    settings_levelPlaceholder: "اسم المستوى...",
    settings_addLevel: "إضافة مستوى",
    settings_subjectsListTitle: "المواد والتخصصات",
    settings_subjectsManagementDesc: "قائمة المواد الدراسية",
    settings_subjectPlaceholder: "اسم المادة...",
    settings_addSubject: "إضافة مادة",
    settings_activitiesTitle: "الأنشطة الرياضية",
    settings_activitiesDesc: "تخصيص قائمة الأنشطة حسب النوع",
    settings_newCategoryPrompt: "صنف جديد...",
    settings_newActivityPrompt: "نشاط جديد...",
    settings_selectCategoryPrompt: "اختر صنفاً لعرض أنشطته",
    settings_criteriaTitle: "معايير التقييم الافتراضية",
    settings_criteriaDesc: "المعايير التي تظهر في التقارير الجديدة",
    settings_criterionPlaceholder: "نص المعيار...",
    settings_addCriterion: "إضافة معيار",
    settings_confirmDeleteCategory: "هل أنت متأكد من حذف الصنف '{0}' وجميع أنشطته؟",
    settings_logoSizeError: "حجم الملف كبير جداً (أقصى حد 500 كيلوبايت)",
    errorBackup: "حدث خطأ أثناء النسخ الاحتياطي",
    errorReadFile: "حدث خطأ أثناء قراءة الملف",
    errorFetchData: "حدث خطأ أثناء جلب البيانات",
    successRestore: "تمت استعادة البيانات بنجاح",
    errorRestore: "خطأ في استعادة البيانات (ملف غير صالح)",
    confirmRestoreTitle: "تأكيد الاستعادة",
    confirmRestoreMessage: "ستؤدي استعادة البيانات إلى استبدال جميع البيانات الحالية. هل أنت متأكد؟",
    confirmRestoreButton: "نعم، استعد البيانات",
    
    // Login
    login_title: "تسجيل الدخول",
    login_subTitle: "فضاء المفتش التربوي",
    login_nameLabel: "الإسم الكامل",
    login_placeholderName: "أدخل إسمك الكامل",
    login_passwordLabel: "كلمة المرور",
    login_placeholderPassword: "أدخل كلمة المرور",
    login_rememberMe: "تذكرني",
    login_button: "دخول",
    login_with_google: "تسجيل الدخول باستخدام جوجل",
    login_success: "تم تسجيل الدخول بنجاح",
    login_errorPassword: "كلمة المرور غير صحيحة",
    login_firstTimeNote: "تنبيه: يتطلب تسجيل الدخول لأول مرة اتصالاً بالإنترنت لتأمين حسابك ومزامنة بياناتك.",
    welcome: "مرحباً",
    themeSwitcher_toDark: "الوضع المظلم",
    themeSwitcher_toLight: "الوضع المضيء",
    about_tooltip: "حول التطبيق",
    
    // Messages
    successInspectorSave: "تم حفظ بيانات المفتش بنجاح",
    errorOccurredWithMessage: "حدث خطأ: {0}",
    successSettingsSave: "تم حفظ الإعدادات بنجاح",
    successTeacherUpdate: "تم تحديث بيانات الأستاذ بنجاح",
    successTeacherAdd: "تمت إضافة الأستاذ بنجاح",
    successTeacherDelete: "تم حذف الأستاذ بنجاح",
    confirmDeleteTitle_teacher: "حذف أستاذ",
    confirmDeleteMessage_teacher: "هل أنت متأكد من حذف هذا الأستاذ؟ سيتم حذف جميع التقارير المرتبطة به.",
    successTeachersImport: "تم استيراد الأساتذة بنجاح",
    confirmImportTitle: "تأكيد الاستيراد",
    confirmImportMessage: "سيتم استبدال القائمة الحالية بالكامل. هل تريد المتابعة؟",
    confirmImportButton: "نعم، استبدل القائمة",
    successReportSave: "تم حفظ التقرير بنجاح",
    errorReportSave: "خطأ في حفظ التقرير",
    successReportDelete: "تم حذف التقرير بنجاح",
    confirmDeleteTitle_report: "حذف التقرير",
    confirmDeleteTitle_academicYear: "حذف الموسم الدراسي",
    confirmDeleteMessage_report: "هل أنت متأكد من حذف هذا التقرير؟ لا يمكن التراجع عن هذه العملية.",
    confirmDeleteMessage_academicYear: "هل تريد فعلا حذف تقارير هذا الموسم الدراسي؟",
    successSlipSave: "تم حفظ جدول الإرسال بنجاح",
    successSlipDelete: "تم حذف جدول الإرسال بنجاح",
    confirmDeleteTitle_slip: "حذف جدول الإرسال",
    confirmDeleteTitle_confirm: "نعم، متأكد",
    confirmDeleteMessage_slip: "هل أنت متأكد من حذف جدول الإرسال هذا؟",
    settings_syncingFromCloud: "جاري التحديث من السحابة... يرجى الانتظار",
    settings_syncingToCloud: "جاري الرفع إلى السحابة... يرجى الانتظار",
    evaluation_draftingAI: "يرجى الانتظار، يتم الآن صياغة التقرير...",
    otherReports_activityTypeLabel: "نوع النشاط (يظهر في الحصيلة)",
    otherReports_activityCategoryLabel: "صنف النشاط",
    otherReports_selectOrCreateActivity: "اختر أو اكتب نوعاً...",
    otherReports_selectOrCreateCategory: "اختر أو اكتب صنف النشاط...",
    otherReports_addToList: "إضافة للأصناف",
    ai_assistant: "مساعد تحرير (AI)",
    ai_instructions_placeholder: "تعليمات إضافية للصياغة (اختياري)...",
    ai_rephrase_button: "صياغة وتدقيق المحتوى (AI)",
    settings_syncSuccess: "تم التحديث من السحابة بنجاح!",
    settings_syncToCloudSuccess: "تم الرفع إلى السحابة بنجاح!",
    settings_syncError: "حدث خطأ أثناء التحديث من السحابة",
    errorOfflineSync: "لا يوجد اتصال بالإنترنت. تعذر المزامنة.",
    errorAuthRequired: "يجب تسجيل الدخول أولاً للرفع إلى السحابة.",
    errorInspectorNameRequired: "يجب إدخال اسم المفتش أولاً في الصفحة الرئيسية",
    errorApiKeyMissingBuild: "مفتاح API الخاص بالذكاء الاصطناعي غير متوفر. يرجى إعداده في إعدادات البيئة.",
    errorOfflineAI: "لا يوجد اتصال بالإنترنت. الذكاء الاصطناعي يتطلب اتصالا نشطا.",
    onlineMode: "أنت متصل بالإنترنت",
    offlineMode: "أنت غير متصل بالإنترنت",
    deliveredStatus: "تم التسليم",
    setAsDelivered: "تحديد كمُسلّم",
    cancelDelivery: "إلغاء التسليم",
    deliverAll: "تسليم الكل",
    clonedAsNew: "نسخ كتقرير جديد",
    noSavedReports: "لا توجد تقارير محفوظة.",
    archive: "الأرشيف",
    "زيارات": "زيارات",
    "تفتيشات": "تفتيشات",
    "إرسالية": "إرسالية",
    "تقرير مهمة": "تقرير مهمة",
    "الترسيم والكفاءة": "الترسيم والكفاءة",
    "أنشطة أخرى": "أنشطة أخرى",
    "التفتيشات والزيارات": "التفتيشات والزيارات",
    "التكوينات": "التكوينات",
    "العمل المشترك": "العمل المشترك",
    logout_success: "تم تسجيل الخروج بنجاح",
    logout: "تسجيل الخروج",
    logoutFromCurrentAccount: "الخروج من حسابك الحالي",
    backupAndAppearance: "النسخ الاحتياطي والمظهر",
    menuList: "القائمة",
    memos: "المذكرات",
    memos_desc: "تدبير والاطلاع على المذكرات",
    memos_management: "إدارة المذكرات",
    otherReports_displayTeachersList: "عرض لائحة الأساتذة",
    otherReports_displayInstitutionsOnly: "عرض لائحة المؤسسات فقط",
    memos_list: "قائمة المذكرات",
    memosWindow: "نافذة المذكرات",
    memo_add_title: "إضافة مذكرة جديدة",
    memo_edit_title: "تعديل مذكرة",
    memo_activity_type_label: "نوع النشاط",
    memo_select_activity_placeholder: "اختر نوع النشاط...",
    memo_title_label: "عنوان المذكرة",
    memo_title_placeholder: "اكتب عنوان المذكرة هنا...",
    memo_content_label: "نص المذكرة",
    memo_content_placeholder: "اكتب نص المذكرة هنا...",
    memo_save_btn: "حفظ المذكرة",
    memo_update_btn: "تحديث المذكرة",
    memo_no_memos: "لا توجد مذكرات مضافة حالياً",
    memo_view_title: "عرض المذكرة",
    memo_empty_list: "قائمة المذكرات فارغة",
    memo_cancel_btn: "إلغاء",
    memo_delete_btn: "حذف",
    memo_view_btn: "عرض",
    memo_edit_btn: "تعديل",
    validation: "المصادقة",
    promotion: "الترقية",
    status: "الوضع",
    searchByTeacherName: "بحث باسم الاستاذ",
    selectInstitutions: "اختر المؤسسات...",
    licensesAndAbsences: "سجل الرخص والغيابات",
    noLicensesOrAbsences: "لا توجد رخص أو غيابات مسجلة لهذا الأستاذ.",
    promotionsTracking: "تتبع الترقيات:",
    gpsIdentifyInstitution: "تحديد المؤسسة الحالية",
    gpsInstitutionPrompt: "لم نتمكن من التعرف على مؤسستك الحالية تلقائياً. يرجى اختيار المؤسسة التي تتواجد بها الآن لربطها بموقعك الحالي (GPS). سيتم حفظ هذا الموقع لتسهيل التعرف عليه في المرات القادمة.",
    saveLocation: "حفظ الموقع",
    memosRelatedToActivity: "المذكرات المرتبطة بهذا النشاط",
    generalStatistics: "إحصائيات عامة",
    visits: "زيارات",
    missionReports: "تقارير مهام",
    correspondence: "مراسلات",
    administrativeReports: "تقارير إدارية",
    eligibleForPromotion: "مستحق للترقية",
    inspections: "تفتيشات",
    other: "أخرى",
    total: "المجموع",
    otherStatsDetails: "تفاصيل الأنشطة الأخرى",
    pace_rapid: "سريع",
    pace_medium: "متوسط",
    pace_slow: "بطيء",
    pace_rapid_full: "النسق السريع",
    pace_medium_full: "النسق المتوسط",
    pace_slow_full: "النسق البطيء",
    reportTypeModal_title: "نوع التقرير",
    currentSeason: "الموسم الحالي",
    firstSemester: "الأسدس الأول",
    secondSemester: "الأسدس الثاني",
    reportTypeModal_description: "اختر نوع المهمة التي تود القيام بها:",
    
    // Professional Card in Inspection Space
    professionalCard_adminInfo: "المعلومات الإدارية",
    professionalCard_inspectionInfo: "آخر تفتيش",
    
    // Add Teacher Choice
    addTeacher_choiceTitle: "إضافة أستاذ",
    addTeacher_manual: "إضافة يدوية",
    addTeacher_excel: "استيراد ملف Excel",
    
    // About
    aboutModal_title: "حول التطبيق",
    aboutModal_philosophyTitle: "فلسفة التطبيق",
    aboutModal_howToUseTitle: "كيفية الاستخدام",
    aboutModal_philosophy_p1: "يعتبر تطبيق 'المفتش' منصة رقمية متكاملة صممت خصيصاً لتلبية الاحتياجات المهنية الدقيقة لمفتشي التربية البدنية والرياضية. ينبثق هذا المشروع من ضرورة عصرنة الممارسة المهنية وتجاوز الأساليب التقليدية في التدبير الإداري والتربوي، مما يتيح للمفتش التركيز أكثر على الجوانب التأطيرية والبيداغوجية.",
    aboutModal_philosophy_p2: "يهدف التطبيق إلى رقمنة شاملة لمسار التفتيش، بدءاً من الأرشفة الذكية لملفات الأساتذة، مروراً بالتحرير الآلي والمدعوم بالذكاء الاصطناعي للتقارير، وصولاً إلى الضبط الدقيق للمراسلات وتوليد الحصيلة السنوية بضغطة زر واحدة، مع ضمان أمن وخصوصية البيانات عبر التخزين المحلي والسحابي المشفر.",
    aboutModal_featuresTitle: "المميزات والوظائف الرئيسية",
    aboutModal_feature1_title: "التدبير الذكي لهيئة التدريس",
    aboutModal_feature1_desc: "قاعدة بيانات مركزية تتيح تتبع المسار المهني لكل أستاذ (الدرجة، الرتبة، تاريخ التوظيف...) مع إمكانية استيراد اللوائح من ملفات Excel وتصنيف الأساتذة حسب المؤسسات والقطاعات (عمومي/خصوصي).",
    aboutModal_feature2_title: "نظام تحرير التقارير المتقدم",
    aboutModal_feature2_desc: "واجهة مرنة لتحرير تقارير التفتيش والزيارات الصفية، مدعومة بمحرك ذكاء اصطناعي لصياغة الملاحظات التربوية بشكل احترافي. يدعم النظام تصدير الوثائق بصيغ Word و PDF جاهزة للطباعة مع الترويسة الرسمية.",
    aboutModal_feature3_title: "فضاء التفتيش والقيادة",
    aboutModal_feature3_desc: "لوحة قيادة تفاعلية توفر رؤية شاملة للخريطة التربوية، حيث يمكن تتبع جداول حصص الأساتذة، وضعياتهم الإدارية، وتحديد المتاحين منهم للزيارة أو التفتيش في الوقت الفعلي.",
    aboutModal_feature4_title: "تدبير المراسلات وجداول الإرسال",
    aboutModal_feature4_desc: "مكتبة من النماذج الجاهزة للمراسلات الإدارية، تقارير الندوات، واللقاءات التربوية. كما يتضمن نظاماً لإنشاء جداول الإرسال (Bordereaux d'envoi) لضبط وتتبع حركة الوثائق الصادرة.",
    aboutModal_feature5_title: "الحصيلة الدورية والإحصائيات",
    aboutModal_feature5_desc: "توليد تلقائي وشامل لحصيلة الأنشطة (الأسدس الأول، الثاني، السنوية) مع رسوم بيانية توضح تطور الأداء. يتضمن النظام أرشيفاً منظماً حسب المواسم الدراسية لسهولة العودة للبيانات السابقة.",
    aboutModal_step1_title: "1. إعداد الملف الشخصي والبيانات الأساسية:",
    aboutModal_step1_desc: "ابدأ بضبط بياناتك المهنية في صفحة 'المفتش'، ثم قم ببناء قاعدة بيانات الأساتذة إما يدوياً أو عبر خاصية الاستيراد السريع من ملف Excel لربح الوقت.",
    aboutModal_step2_title: "2. تنفيذ المهام الميدانية والتربوية:",
    aboutModal_step2_desc: "استخدم الأزرار السريعة في الواجهة الرئيسية لتوثيق الزيارات أو التفتيشات. يمكنك استغلال الذكاء الاصطناعي لتحسين صياغة الملاحظات وضمان جودة التقرير.",
    aboutModal_step3_title: "3. الحفظ، الأرشفة والتصدير الرقمي:",
    aboutModal_step3_desc_A: "يتم حفظ جميع تحركاتك تلقائياً في ذاكرة الجهاز لضمان العمل دون إنترنت.",
    aboutModal_step3_desc_B: "يمكنك في أي وقت معاينة الوثائق وتصديرها بصيغ احترافية (Word/PDF) أو مشاركتها مباشرة عبر الوسائط الرقمية.",
    aboutModal_step4_title: "4. الأمان والنسخ الاحتياطي المنتظم:",
    aboutModal_step4_desc: "احرص على إجراء نسخ احتياطي لبياناتك دورياً من الإعدادات. كما يمكنك تفعيل المزامنة السحابية لضمان الوصول لبياناتك من أي جهاز آخر بأمان تام.",
    aboutModal_closing: "تم تطوير هذا التطبيق كمساهمة تقنية لتجويد منظومة التفتيش التربوي",
    
    // Image Viewer
    zoomIn: "تكبير",
    zoomOut: "تصغير",
    resetZoom: "إعادة تعيين",
    rotate: "تدوير",
    reset: "إعادة تعيين",
    
    // Days
    day_monday: "الإثنين",
    day_tuesday: "الثلاثاء",
    day_wednesday: "الأربعاء",
    day_thursday: "الخميس",
    day_friday: "الجمعة",
    day_saturday: "السبت",
    day_sunday: "الأحد",
    footerText: "جميع الحقوق محفوظة &copy; 2025 - تطبيق المفتش التربوي",
    
    // FR - French Labels in AR context (for some reason they were here)
    teacher_fullNameFr: "اسم الأستاذ(ة) بالفرنسية",
    teacher_frameworkFr: "الإطار (بالفرنسية)",
    teacher_subjectFr: "التخصص (بالفرنسية)",
    teacher_institutionFr: "المؤسسة (بالفرنسية)",
    inspectorModal_fullNameFr: "الإسم الكامل (بالفرنسية)",
    inspectorModal_fullNameFrPlaceholder: "أدخل الإسم الكامل بالفرنسية هنا...",
    inspectorModal_frameworkFr: "الإطار (بالفرنسية)",
    inspectorModal_academyFr: "الأكاديمية (بالفرنسية)",
    inspectorModal_directorateFr: "المديرية (بالفرنسية)",
    inspectorModal_subjectFr: "التخصص (بالفرنسية)",
    inspectorModal_regionalDirectorTitleFr: "صفة المسؤول الإقليمي (FR)",
    lang_all: "الكل",
    lang_fr_btn: "Français",
    lang_ar_btn: "العربية",
    filter_language: "تصفية حسب اللغة",
    calendar_next: "التالي",
    calendar_previous: "السابق",
    calendar_today: "اليوم",
    calendar_month: "شهر",
    calendar_week: "أسبوع",
    calendar_day: "يوم",
    calendar_agenda: "أجندة",
    calendar_date: "تاريخ",
    calendar_time: "وقت",
    calendar_event: "حدث",
    calendar_no_events: "لا توجد أحداث في هذه الفترة.",
    event_completed: "منجزة",
    event_add_new: "إضافة حدث جديد",
    event_day_title: "أحداث يوم",
    event_edit_title: "تعديل الحدث",
    event_add_title: "إضافة حدث",
    event_title_label: "عنوان الحدث",
    event_title_placeholder: "مثال: زيارة تفتيشية، ندوة تربوية...",
    event_location_label: "المكان",
    event_location_placeholder: "مثال: مدرسة ابن خلدون، القاعة 4...",
    event_from_label: "من",
    event_to_label: "إلى",
    event_importance_label: "الأهمية",
    event_importance_low: "عادية (أزرق)",
    event_importance_medium: "متوسطة (برتقالي)",
    event_importance_high: "عالية (أحمر)",
    event_completed_task: "تم إنجاز المهمة",
    event_zoom_hint: "انقر على المعاينة للتكبير/التصغير (Zoom)",
    notification_settings_title: "إعدادات الإشعارات المحلية",
    notification_no_events: "لا توجد أنشطة في البرنامج السنوي لجدولتها. يرجى إضافة أنشطة أولاً.",
    notification_description: "سيتم إرسال إشعارين لكل نشاط قادم. يمكنك تحديد وقت الإشعارات أدناه:",
    notification_test_btn: "إرسال إشعار تجريبي الآن",
    notification_schedule_btn: "جدولة إشعارات البرنامج",
    notification_scheduled: "تمت جدولة إشعارات أنشطتك بنجاح",
    notification_error_not_supported: "الإشعارات غير مدعومة على هذا المتصفح",
    notification_error_denied: "تم رفض أذونات الإشعارات",
    notification_error_failed: "فشل في جدولة الإشعارات",
    month_january: "يناير",
    month_february: "فبراير",
    month_march: "مارس",
    month_april: "أبريل",
    month_may: "ماي",
    month_june: "يونيو",
    month_july: "يوليوز",
    month_august: "غشت",
    month_september: "شتنبر",
    month_october: "أكتوبر",
    month_november: "نونبر",
    month_december: "دجنبر",
    annual_program: "البرنامج السنوي",
    annual_project: "مشروع برنامج العمل السنوي",
    enable_notifications: "تفعيل الإشعارات المحلية",
    export_calendar: "تصدير للتقويم",
    digital_summary: "الحصيلة الرقمية",
    preview_print_summary: "معاينة وطباعة الحصيلة",
    notification_first: "الإشعار الأول",
    notification_second: "الإشعار الثاني",
    notification_reminder_before: "تذكير قبل:",
    notification_browser_note: "ملاحظة: أنت تستخدم نسخة المتصفح. الإشعارات المجدولة (في الخلفية) تعمل بشكل موثوق فقط عند تثبيت التطبيق على الهاتف (Android/iOS).",
    time_weeks: "أسابيع",
    time_days: "أيام",
    time_hours: "ساعات",
  },
  fr: {
    appTitle: "Inspecteur Intelligent",
    appDescription: "Gestion des activités de l'inspecteur pédagogique",
    
    // Inspector Modal
    inspectorModal_title: "Données de l'Inspecteur",
    inspectorModal_fullName: "Nom Complet",
    inspectorModal_fullNameFr: "Nom Complet (Français)",
    inspectorModal_fullNameFrPlaceholder: "Entrer le nom complet en français...",
    inspectorModal_financialId: "N° de Somme",
    inspectorModal_financialIdPlaceholder: "N° de Somme...",
    inspectorModal_regionalDirectorTitle: "Titre du Responsable Provincial",
    inspectorModal_regionalDirectorTitlePlaceholder: "Ex: Directeur Provincial",
    inspectorModal_framework: "Cadre",
    inspectorModal_selectFramework: "Choisir le Cadre",
    "أستاذ التعليم الإبتدائي": "Enseignant du Primaire",
    "أستاذ التعليم الثانوي الإعدادي": "Enseignant du Secondaire Collégial",
    "أستاذ التعليم الثانوي التأهيلي": "Enseignant du Secondaire Qualifiant",
    "أستاذ التعليم الإبتدائي ": "Enseignant du Primaire",
    "أستاذ التعليم الثانوي الإعدادي ": "Enseignant du Secondaire Collégial",
    "أستاذ التعليم الثانوي التأهيلي ": "Enseignant du Secondaire Qualifiant",
    "أستاذ التعليم الثانوي الاعدادي": "Enseignant du Secondaire Collégial",
    "أستاذ التعليم الابتدائي": "Enseignant du Primaire",
    "أستاذ": "Enseignant",
    "أستاذة": "Enseignante",
    "الدرجة 3": "Grade 3",
    "الدرجة 2": "Grade 2",
    "الدرجة 1": "Grade 1",
    "الدرجة الثانية": "Grade 2",
    "الدرجة الثالثة": "Grade 3",
    "الدرجة الأولى": "Grade 1",
    "الدرجة الممتازة": "Grade Exceptionnel",
    "خارج السلم": "Hors Échelle",
    deleteImage: "Supprimer l'image",
    assignedClassesTitle: "Classes assignées (Important pour l'emploi du temps)",
    noClassesAdded: "Aucune classe n'a été ajoutée.",
    editTimetable: "Modifier l'emploi du temps",
    "كرة السلة": "Basketball",
    "كرة اليد": "Handball",
    "الكرة الطائرة": "Volleyball",
    "كرة القدم": "Football",
    "الجمباز": "Gymnastique",
    "ألعاب القوى": "Athlétisme",
    "السرعة": "Vitesse",
    "الوثب الطويل": "Saut en longueur",
    "دفع الجلة": "Lancer du poids",
    "سباق التتابع": "Course de relais",
    "سباق الحواجز": "Course de haies",
    "الأسس": "Les Fondamentaux",
    "التموضع": "Placement",
    "التنقل": "Déplacement",
    "التمريرة الصدرية": "Passe de poitrine",
    "التمريرة بالارتداد": "Passe à rebond",
    "المحاورة": "Dribble",
    "التصويب": "Tir",
    "الدفاع": "Défense",
    "الهجوم": "Attaque",
    "المباراة": "Match",
    "القوانين": "Règlement",
    "التحكيم": "Arbitrage",
    // Academies Mappings
    "جهة الشرق": "Région de l'Oriental",
    "جهة الرباط-سلا-القنيطرة": "Région de Rabat-Salé-Kénitra",
    "جهة فاس-مكناس": "Région de Fès-Meknès",
    "جهة مراكش-آسفي": "Région de Marrakech-Safi",
    "جهة سوس ماسة": "Région de Souss-Massa",
    "جهة طنجة تطوان الحسيمة": "Région de Tanger-Tétouan-Al Hoceïma",
    "جهة الدار البيضاء سطات": "Région de Casablanca-Settat",
    "جهة بني ملال خنيفرة": "Région de Béni Mellal-Khénifra",
    "جهة درعة تافيلالت": "Région de Drâa-Tafilalet",
    "جهة كلميم واد نون": "Région de Guelmim-Oued Noun",
    "جهة العيون الساقية الحمراء": "Région de Laâyoune-Sakia El Hamra",
    "جهة الداخلة وادي الذهب": "Région de Dakhla-Oued Ed-Dahab",
    // Directorates / Cities Mappings
    "تاوريرت": "Taourirt",
    "الرباط": "Rabat",
    "فاس": "Fès",
    "مراكش": "Marrakech",
    "أكادير إداوتنان": "Agadir Ida-Outanane",
    "تارودانت": "Taroudant",
    "طنجة أصيلة": "Tanger-Assilah",
    "وجدة أنجاد": "Oujda-Angad",
    "الدار البيضاء": "Casablanca",
    "القنيطرة": "Kénitra",
    "سلا": "Salé",
    "تمارة": "Témara",
    "الصخيرات": "Skhirat",
    "بركان": "Berkane",
    "الناظور": "Nador",
    "الدريوش": "Driouch",
    "جرسيف": "Guercif",
    "بولمان": "Boulemane",
    "ميدلت": "Midelt",
    "إفران": "Ifrane",
    "الحاجب": "El Hajeb",
    "صفرو": "Sefrou",
    "مولاي يعقوب": "Moulay Yacoub",
    "تاونات": "Taounate",
    "تازة": "Taza",
    "مكناس": "Meknès",
    // Subject Mapping
    "التربية البدنية والرياضية": "Éducation Physique et Sportive",
    // Administrative Mappings
    "المدير الإقليمي": "Directeur Provincial",
    "المدير الجهوي": "Directeur Régional",
    "وزارة التربية الوطنية والتعليم الأولي والرياضة": "Ministère de l'Éducation Nationale, du Préscolaire et des Sports",
    score_label: "Note",
    inspectorModal_academy: "Académie",
    inspectorModal_directorate: "Direction Provinciale",
    inspectorModal_subject: "Spécialité",
    inspectorModal_subjectPlaceholder: "Ex: Éducation Physique et Sportive",
    inspectorModal_securityTitle: "Sécurité",
    inspectorModal_newPassword: "Nouveau Mot de Passe",
    inspectorModal_confirmPassword: "Confirmer le Mot de Passe",
    inspectorModal_passwordPlaceholder: "Laisser vide si inchangé",
    inspectorModal_passwordMismatch: "Les mots de passe ne correspondent pas",
    framework_inspector_primary: "Inspecteur de l'Enseignement Primaire",
    framework_inspector_middle: "Inspecteur de l'Enseignement Secondaire Collégial",
    framework_inspector_high: "Inspecteur de l'Enseignement Secondaire Qualifiant",
    select_academy: "Choisir l'Académie",
    select_directorate: "Choisir la Direction",
    language: "Langue",
    save: "Enregistrer",
    delete: "Supprimer",
    cancel: "Annuler",
    inspectorModal_cancelBtn: "Annuler",
    all: "Tout",
    confirmDelete: "Confirmer",
    clear: "Effacer",
    alert_fill_required: "Veuillez remplir les champs obligatoires",
    evaluation_subject: "Matière",
    search: "Recherche",
    "Inspections": "Inspections",
    "Visites": "Visites",
    "Service des Affaires Pédagogiques": "Service des Affaires Pédagogiques",
    "أنشطة أخرى - رياضة مدرسية": "Autres activités - Sport scolaire",
    "أنشطة أخرى - المصادقة على التوزيع الحلقي": "Autres activités - Validation de la répartition",
    "درس تجريبي": "Leçon expérimentale",
    "الدروس التجريبية": "Leçons expérimentales",
    "أنشطة أخرى - مراسلة": "Autres activités - Correspondance",
    "أنشطة أخرى - المصادقة على جداول الحصص": "Autres activités - Validation des emplois du temps",
    "أنشطة أخرى - تقرير إداري": "Autres activités - Rapport administratif",
    "أنشطة أخرى - امتحانات الباكالوريا": "Autres activités - Examens du Baccalauréat",
    "الندوات واللقاءات التربوية": "Séminaires et Rencontres Pédagogiques",
    "الترسيم والكفاءة": "Titularisation et Compétence",
    "أنشطة أخرى": "Autres activités",
    "التفتيشات والزيارات": "Inspections et Visites",
    "التكوينات": "Formations",
    "العمل المشترك": "Travail collectif",
    
    // Home
    home_pageTitle: "Accueil",
    home_inspectorCardTitle: "Inspecteur",
    home_inspectorCardDesc: "Modifier les données personnelles et administratives",
    home_teachersCardTitle: "Corps Enseignant",
    home_teachersCardDesc: "Gestion des dossiers des enseignants",
    home_inspectionSpaceCardTitle: "Espace d'Inspection",
    home_reportsCardTitle: "Rapports d'Inspection",
    home_reportsCardDesc: "Consulter les rapports d'inspection et de visites",
    home_otherReportsCardTitle: "Autres Rapports",
    home_otherReportsCardDesc: "Correspondances et rapports administratifs",
    home_transmissionSlipCardTitle: "Bordereau d'Envoi",
    home_transmissionSlipCardDesc: "Document de suivi des correspondances",
    home_activitySummaryCardTitle: "Programme et Bilan",
    home_activitySummaryCardDesc: "Bilan périodique et annuel des activités",
    home_settingsCardTitle: "Paramètres",
    home_statisticsCardTitle: "Statistiques",
    home_statisticsCardDesc: "Indicateurs et graphiques de performance",
    home_researchCardTitle: "Recherche Pédagogique",
    home_researchCardDesc: "Guide pour préparer des recherches pédagogiques",
    
    // Teachers List
    teachersList_pageTitle: "Liste des Enseignants",
    teachersList_selectTitle: "Choisir un Enseignant",
    teachersList_addTeacher: "Ajouter un Enseignant",
    teachersList_searchLabel: "Rechercher",
    sidebar_inspectorWindow: "Espace de l'Inspecteur",
    sidebar_inspectorWindowDesc: "Modifier les données de l'inspecteur",
    sidebar_appVersion: "Inspecteur Intelligent v1.1",
    sidebar_localBackup: "Sauvegarde locale",
    sidebar_localRestore: "Restauration locale",
    sidebar_cloudBackup: "Sauvegarde cloud",
    sidebar_cloudRestore: "Restauration cloud",
    teachersList_searchPlaceholder: "Nom ou établissement...",
    teachersList_selectAlertTitle: "Alerte",
    teachersList_selectAlertText: "Veuillez choisir un enseignant dans la liste",
    teachersList_addTeachersFirst: "Veuillez d'abord ajouter des enseignants",
    teachersList_colFullName: "Nom Complet",
    teachersList_colInstitution: "Établissement",
    teachersList_colFramework: "Cadre",
    teachersList_colLastScore: "Dernière Note",
    teachersList_colActions: "Actions",
    teachersList_noResults: "Aucun résultat",
    select: "Sélectionner",
    viewDetails: "Détails",
    edit: "Modifier",
    importFromExcel: "Importer depuis Excel",
    importHelp_title: "Instructions d'Importation",
    teachersList_exportTitle: "Exporter la liste des enseignants",
    teachersList_exportBtn: "Exporter la liste",
    settings_platformConfigTitle: "Synchronisation des enseignants (Firebase)",
    settings_platformConfigHelp: "Utilisez cette option pour synchroniser la liste des enseignants depuis la base de données centrale (Firebase).",
    importHelp_intro: "Le fichier Excel doit contenir les colonnes suivantes :",
    importHelp_col1: "<b>fullName</b> : Nom complet",
    importHelp_col2: "<b>employeeId</b> : N° de somme",
    importHelp_col3: "<b>genre</b> : Genre (male/female)",
    importHelp_col4: "<b>framework</b> : Cadre",
    importHelp_col5: "<b>institution</b> : Établissement",
    importHelp_col6: "<b>subject</b> : Matière",
    importHelp_col7: "<b>grade</b> : Grade",
    importHelp_col8: "<b>rank</b> : Échelon",
    importHelp_col9: "<b>lastInspectionScore</b> : Dernière note d'inspection",
    importHelp_col10: "<b>lastInspectionDate</b> : Date de la dernière inspection (YYYY-MM-DD)",
    importHelp_col11: "<b>lastInspector</b> : Nom de l'inspecteur précédent",
    importHelp_col12: "<b>image</b> : Lien de l'image (optionnel)",
    importHelp_col13: "<b>promotionPace</b> : Rythme d'avancement (rapid/medium/slow)",
    importHelp_button_proceed: "Continuer l'Importation",
    errorImportInvalidFormat: "Format de fichier invalide",
    errorImport: "Erreur lors de l'importation",
    
    // Teacher Detail
    teacherDetail_pageTitle: "Dossier de l'Enseignant",
    teacherDetail_addVisit: "Ajouter une Visite",
    teacherDetail_addInspection: "Ajouter une Inspection",
    teacherDetail_infoCardTitle: "Informations Professionnelles",
    teacherDetail_historyCardTitle: "Historique des Visites et Inspections",
    teacherDetail_noReports: "Aucun rapport enregistré",
    teacher_female: "Mme l'Enseignante",
    teacher_male: "Mr l'Enseignant",
    teacher_fullName: "Nom Complet",
    teacher_fullNameFr: "Nom Complet (Français)",
    teacher_subject: "Matière",
    teacher_subjectFr: "Matière (Français)",
    teacher_lastScore: "Dernière Note",
    teacher_employeeId: "N° de Somme",
    teacher_grade: "Grade",
    teacher_lastDate: "Dernière Date d'Inspection",
    teacher_framework: "Cadre",
    teacher_frameworkFr: "Cadre (Français)",
    teacher_rank: "Échelon",
    teacher_lastInspector: "Inspecteur",
    teacher_institution: "Établissement",
    teacher_institutionFr: "Établissement (Français)",
    teacher_genre: "Genre",
    teacher_recruitmentDate: "Date de Recrutement",
    teacher_tenureDate: "Date de Titularisation",
    teacher_gradeDate: "Date d'Effet du Grade",
    teacher_rankDate: "Date d'Effet de l'Échelon",
    genre_male: "Masculin",
    genre_female: "Féminin",
    back: "Retour",
    home: "Accueil",
    visit: "Visite",
    inspection: "Inspection",
    reportDatePrefix: "Date",
    reportHasLessonPlan: "Plan de leçon joint",
    viewExport: "Aperçu / Exporter",
    sector_label: "Secteur",
    sector_public: "Public",
    sector_private: "Privé",
    
    // Reports Form / Evaluation
    reportModal_lessonObservation: "Observations sur la leçon",
    evaluation_field_tools: "Moyens Didactiques",
    evaluation_field_studentCount: "Effectif",
    evaluation_field_class: "Classe",
    evaluation_field_level: "Niveau",
    evaluation_field_activity: "Activité",
    evaluation_field_activityCategory: "Catégorie d'activité",
    evaluation_field_lessonGoal: "Objectif de la séance",
    evaluation_criterion: "Critère",
    reportModal_criteria: "Critères et Indicateurs",
    report_dateLabel: "Fait le",
    report_awardedScore: "Note Attribuée",
    signature_title_1: "Signature de l'Inspecteur",
    signature_regionalDirector: "Signature du {regionalDirectorTitle}",
    signature_institutionDirector: "Signature du Directeur de l'Établissement",
    errorPopupBlocker: "Fenêtre bloquée. Veuillez autoriser les popups pour l'impression.",
    errorExportLibrary: "Bibliothèques d'exportation non disponibles",
    close: "Fermer",
    share: "Partager",
    exportWord: "Exporter Word",
    exportPdf: "Exporter PDF",
    print: "Imprimer",
    inspectionReport: "Rapport d'Inspection",
    visitReport: "Rapport de Visite",
    ministryLogoAlt: "Logo du Ministère",
    regionalAcademyLabel: "Académie Régionale:",
    regionalDirectorateLabel: "Direction Provinciale:",
    department_pedagogicalAffairs: "Service des Affaires Pédagogiques",
    
    // Reports List
    reportsList_pageTitle: "Archive des Rapports",
    reportsList_newReport: "Nouveau Rapport",
    reportsList_filterTitle: "Filtrer",
    teacher: "Enseignant",
    reportsList_allTeachers: "Tous les Enseignants",
    reportsList_reportType: "Type de Rapport",
    reportsList_allTypes: "Tous",
    reportsList_academicYear: "Année Scolaire",
    reportsList_allYears: "Toutes les Années",
    type: "Type",
    date: "Date",
    score: "Note",
    actions: "Actions",
    reportsList_noResults: "Aucun rapport trouvé",
    
    // Evaluation Page
    evaluation_scoreLabel: "Note proposée (sur 20)",
    evaluation_scoreRequired: "Veuillez saisir la note",
    evaluation_generatingAI: "Génération des observations par l'IA...",
    evaluation_generateAIBtn: "Générer les observations (AI)",
    evaluation_generateAIForCriterion: "Rédiger avec l'IA",
    evaluation_mustHaveOneCriterion: "Au moins un critère est requis",
    evaluation_fieldValuePlaceholder: "Saisir le contenu...",
    reportModal_lessonPlanSectionTitle: "Image du plan de leçon (optionnel)",
    evaluation_changeLessonPlanImage: "Changer l'image",
    evaluation_removeLessonPlanImage: "Supprimer l'image",
    evaluation_takePhoto: "Prendre une photo",
    evaluation_uploadImage: "Télécharger une image",
    evaluation_criterionNamePlaceholder: "Nom du critère",
    evaluation_commentsPlaceholder: "Observations sur {0}...",
    evaluation_addCriterion: "Ajouter un critère",
    otherReportModal_title: "Aperçu du Rapport",
    settings_selectCategory: "Choisir la catégorie",
    settings_selectActivity: "Choisir l'activité",
    evaluation_selectLevel: "Choisir le niveau",
    exportExcel: "Exporter Excel",
    exportHtml: "Exporter HTML",
    reportModal_newScore: "Note attribuée",
    report: "Rapport",
    delivered: "Délivré",
    mark_as_delivered: "Marquer comme délivré",
    unnamedField: "Sans titre",
    reportTemplate_standard: 'Rapport Descriptif',
    reportTemplate_network: 'Grille d\'Inspection',
    overallAssessment: 'Appréciation Globale',
    overallAssessmentPlaceholder: 'Saisir l\'appréciation globale ici...',
    achievementLevel_placeholder: 'Niveau d\'acquisition',
    achievementLevel_1: 'Non acquis',
    achievementLevel_2: 'En cours d\'acquisition',
    achievementLevel_3: 'Acquis',
    achievementLevel_4: 'Expert / Maîtrisé',
    evaluation_network_domains: "Domaines",
    evaluation_network_indicators: "Indicateurs",
    evaluation_network_achievementLevel: "Niveau de réalisation",
    evaluation_network_observations: "Observations et orientations",
    evaluation_notEvaluated: "Non évalué",

    // Settings
    settings_pageTitle: "Paramètres",
    settings_tab_general: "Général",
    settings_tab_reports: "Rapports",
    settings_fontSize: "Contrôle de la taille de la police pour toute l'application",
    fontSize_reset: "Réinitialiser",
    settings_ministryTitle: "En-tête des Rapports",
    settings_ministryDesc: "Personnaliser le logo et les données administratives",
    settings_ministryLogoLabel: "Logo du Ministère (Arabe)",
    settings_ministryLogoFrLabel: "Logo du Ministère (Français)",
    settings_changeLogo: "Changer le Logo",
    settings_logoSpecs: "Utilisez de préférence une image PNG transparente",
    settings_logoHeight: "Hauteur du Logo (AR)",
    settings_logoHeightFr: "Hauteur du Logo (FR)",
    settings_aiConfig: "Paramètres IA",
    settings_geminiApiKey: "Clé API Gemini",
    settings_geminiApiKeyHelp: "Requise pour utiliser l'IA dans les rapports. Obtenez-la gratuitement sur Google AI Studio.",
    settings_getApiKey: "Obtenir la clé ici",
    settings_syncFromCloudDesc: "Mettre à jour l'application avec les dernières données enregistrées dans le cloud :",
    settings_syncToCloudDesc: "Enregistrer vos données actuelles dans le cloud (pour la synchronisation avec d'autres appareils) :",
    settings_syncToCloudButton: "Téléverser vers le cloud (Enregistrer)",
    settings_syncFromCloudButton: "Mettre à jour depuis le cloud (Récupérer)",
    settings_syncFromCloudConfirmTitle: "Mise à jour depuis le cloud",
    settings_syncFromCloudConfirmMessage: "Êtes-vous sûr de vouloir récupérer les données du cloud ? Toutes vos données actuelles seront remplacées.",
    settings_academiesTitle: "Académies",
    settings_academiesDesc: "Liste des Académies Régionales",
    settings_academyPlaceholder: "Nom de l'académie...",
    settings_addAcademy: "Ajouter une académie",
    settings_directoratesTitle: "Directions",
    settings_directoratesDesc: "Liste des Directions Provinciales",
    settings_directoratePlaceholder: "Nom de la direction...",
    settings_addDirectorate: "Ajouter une direction",
    settings_departmentsTitle: "Services et Départements",
    settings_departmentsDesc: "Destinataires (Chefs de services...)",
    settings_departmentPlaceholder: "Nom du service...",
    settings_addDepartment: "Ajouter un service",
    settings_backupRestoreTitle: "Sauvegarde et Restauration",
    settings_backupRestoreDesc: "Sauvegarder les données localement ou les restaurer",
    settings_backupButton: "Télécharger Sauvegarde",
    settings_restoreButton: "Restaurer Sauvegarde",
    settings_levelsTitle: "Niveaux Scolaires",
    settings_levelsDesc: "Niveaux disponibles dans les rapports",
    settings_levelPlaceholder: "Nom du niveau...",
    settings_addLevel: "Ajouter un niveau",
    settings_subjectsListTitle: "Matières et Spécialités",
    settings_subjectsManagementDesc: "Liste des matières",
    settings_subjectPlaceholder: "Nom de la matière...",
    settings_addSubject: "Ajouter une matière",
    settings_activitiesTitle: "Activités Sportives",
    settings_activitiesDesc: "Personnaliser la liste des activités par catégorie",
    settings_criteriaTitle: "Critères d'Évaluation par Défaut",
    settings_criteriaDesc: "Les critères qui apparaissent dans les nouveaux rapports",
    settings_newCategoryPrompt: "Nouvelle catégorie...",
    settings_newActivityPrompt: "Nouvelle activité...",
    settings_selectCategoryPrompt: "Choisissez une catégorie pour voir ses activités",
    settings_criterionPlaceholder: "Texte du critère...",
    settings_addCriterion: "Ajouter un critère",
    settings_confirmDeleteCategory: "Êtes-vous sûr de supprimer la catégorie '{0}' et toutes ses activités ?",
    settings_logoSizeError: "La taille du fichier est trop grande (max 500 KB)",
    errorBackup: "Erreur lors de la sauvegarde",
    errorReadFile: "Erreur lors de la lecture du fichier",
    errorFetchData: "Erreur lors de la récupération des données",
    successRestore: "Données restaurées avec succès",
    errorRestore: "Erreur de restauration des données (fichier invalide)",
    confirmRestoreTitle: "Confirmer la restauration",
    confirmRestoreMessage: "La restauration remplacera toutes les données actuelles. Êtes-vous sûr ?",
    confirmRestoreButton: "Oui, restaurer les données",
    
    // Messages
    successInspectorSave: "Données de l'inspecteur sauvegardées avec succès",
    errorOccurredWithMessage: "Une erreur est survenue: {0}",
    successSettingsSave: "Les modifications ont été enregistrées avec succès.",
    successTeacherUpdate: "Données de l'enseignant mises à jour avec succès",
    successTeacherAdd: "Enseignant ajouté avec succès",
    successTeacherDelete: "Enseignant supprimé avec succès",
    confirmDeleteTitle_teacher: "Supprimer un enseignant",
    confirmDeleteMessage_teacher: "Êtes-vous sûr de supprimer cet enseignant ? Tous les rapports associés seront supprimés.",
    successTeachersImport: "Enseignants importés avec succès",
    confirmImportTitle: "Confirmer l'importation",
    confirmImportMessage: "La liste actuelle sera entièrement remplacée. Voulez-vous continuer ?",
    confirmImportButton: "Oui, remplacer la liste",
    successReportSave: "Rapport sauvegardé avec succès",
    errorReportSave: "Erreur lors de la sauvegarde du rapport",
    successReportDelete: "Rapport supprimé avec succès",
    confirmDeleteTitle_report: "Supprimer le rapport",
    confirmDeleteTitle_academicYear: "Supprimer l'année scolaire",
    confirmDeleteMessage_report: "Êtes-vous sûr de supprimer ce rapport ? Cette opération est irréversible.",
    confirmDeleteMessage_academicYear: "Voulez-vous vraiment supprimer les rapports de cette année scolaire ?",
    successSlipSave: "Bordereau enregistré avec succès",
    successSlipDelete: "Bordereau supprimé avec succès",
    confirmDeleteTitle_slip: "Supprimer le bordereau",
    confirmDeleteMessage_slip: "Êtes-vous sûr de supprimer ce bordereau d'envoi ?",
    confirmDeleteTitle_confirm: "Oui, confirmer",
    settings_syncingFromCloud: "Mise à jour depuis le cloud... Veuillez patienter",
    settings_syncingToCloud: "Envoi vers le cloud... Veuillez patienter",
    evaluation_draftingAI: "Veuillez patienter, le rapport est en cours de rédaction...",
    otherReports_activityTypeLabel: "Type d'activité (apparaît dans le bilan)",
    otherReports_activityCategoryLabel: "Catégorie d'activité",
    otherReports_selectOrCreateActivity: "Choisir ou saisir un type...",
    otherReports_selectOrCreateCategory: "Choisir ou saisir une catégorie...",
    otherReports_addToList: "Ajouter à la liste",
    ai_assistant: "Assistant de rédaction (IA)",
    ai_instructions_placeholder: "Instructions supplémentaires (Optionnel)...",
    ai_rephrase_button: "Reformuler et corriger (IA)",
    settings_syncSuccess: "Mise à jour depuis le cloud réussie !",
    settings_syncToCloudSuccess: "Envoi vers le cloud réussi !",
    settings_syncError: "Une erreur est survenue lors de la mise à jour depuis le cloud",
    errorOfflineSync: "Pas de connexion internet. Synchronisation impossible.",
    errorAuthRequired: "Vous devez vous connecter d'abord pour synchroniser avec le cloud.",
    errorInspectorNameRequired: "Vous devez d'abord saisir le nom de l'inspecteur sur la page d'accueil",
    errorApiKeyMissingBuild: "La clé API de l'IA est manquante. Veuillez la configurer dans les paramètres.",
    errorOfflineAI: "Pas de connexion internet. L'IA nécessite une connexion active.",
    onlineMode: "Vous êtes en ligne",
    offlineMode: "Vous êtes hors ligne",
    
    // Professional Card in Inspection Space
    professionalCard_adminInfo: "Informations Administratives",
    professionalCard_inspectionInfo: "Dernière inspection",
    
    // Add Teacher Choice
    addTeacher_choiceTitle: "Ajouter un enseignant",
    addTeacher_manual: "Saisie manuelle",
    addTeacher_excel: "Importer fichier Excel",
    
    // Image Viewer
    zoomIn: "Zoom Avant",
    zoomOut: "Zoom Arrière",
    resetZoom: "Réinitialiser",
    rotate: "Tourner",
    reset: "Réinitialiser",
    
    // Login
    login_title: "Connexion",
    login_subTitle: "Espace de l'Inspecteur Pédagogique",
    login_nameLabel: "Nom Complet",
    login_placeholderName: "Entrez votre nom complet",
    login_passwordLabel: "Mot de Passe",
    login_placeholderPassword: "Entrez le mot de passe",
    login_rememberMe: "Se souvenir de moi",
    login_button: "Connexion",
    login_with_google: "Se connecter avec Google",
    login_success: "Connexion réussie",
    login_errorPassword: "Mot de passe incorrect",
    login_firstTimeNote: "Attention : La première connexion nécessite une connexion Internet pour sécuriser votre compte et synchroniser vos données.",
    welcome: "Bienvenue",
    themeSwitcher_toDark: "Mode Sombre",
    themeSwitcher_toLight: "Mode Clair",
    about_tooltip: "À propos",
    logout: "Déconnexion",
    logout_success: "Déconnexion réussie",
    logoutFromCurrentAccount: "Se déconnecter du compte actuel",
    backupAndAppearance: "Sauvegarde et Apparence",
    menuList: "Menu",
    memos: "Notes et circulaires",
    memos_desc: "Gestion et consultation des notes et circulaires",
    memos_management: "Gestion des notes et circulaires",
    memos_list: "Liste des notes et circulaires",
    memosWindow: "Fenêtre des notes et circulaires",
    memo_add_title: "Ajouter une note/circulaire",
    memo_edit_title: "Modifier la note/circulaire",
    memo_activity_type_label: "Type d'activité",
    memo_select_activity_placeholder: "Choisir le type d'activité...",
    memo_title_label: "Titre de la note",
    memo_title_placeholder: "Saisir le titre ici...",
    memo_content_label: "Contenu de la note",
    memo_content_placeholder: "Saisir le contenu ici...",
    memo_save_btn: "Enregistrer la note",
    memo_update_btn: "Mettre à jour la note",
    memo_no_memos: "Aucune note ajoutée pour le moment",
    memo_view_title: "Voir la note",
    memo_empty_list: "La liste des notes est vide",
    memo_cancel_btn: "Annuler",
    memo_delete_btn: "Supprimer",
    memo_view_btn: "Voir",
    memo_edit_btn: "Modifier",
    validation: "Validation",
    promotion: "Promotion",
    status: "Statut",
    searchByTeacherName: "Recherche par nom d'enseignant",
    selectInstitutions: "Choisir les établissements...",
    licensesAndAbsences: "Registre des congés et absences",
    noLicensesOrAbsences: "Aucun congé ou absence enregistré pour cet enseignant.",
    promotionsTracking: "Suivi des promotions :",
    gpsIdentifyInstitution: "Identifier l'établissement actuel",
    gpsInstitutionPrompt: "Nous n'avons pas pu identifier automatiquement l'établissement. Veuillez choisir l'établissement actuel pour le lier à votre position (GPS). Cet emplacement sera sauvegardé pour faciliter la reconnaissance à l'avenir.",
    saveLocation: "Enregistrer l'emplacement",
    memosRelatedToActivity: "Notes et circulaires liées à cette activité",
    generalStatistics: "Statistiques générales",
    visits: "Visites",
    missionReports: "Rapports de mission",
    correspondence: "Correspondances",
    administrativeReports: "Rapports administratifs",
    eligibleForPromotion: "Éligible à la promotion",
    inspections: "Inspections",
    other: "Autre",
    total: "Total",
    otherStatsDetails: "Détails des autres activités",
    pace_rapid: "Rapide",
    pace_medium: "Moyen",
    pace_slow: "Lent",
    pace_rapid_full: "Cadence rapide",
    pace_medium_full: "Cadence moyenne",
    pace_slow_full: "Cadence lente",
    reportTypeModal_title: "Type de rapport",
    currentSeason: "Saison en cours",
    firstSemester: "1er semestre",
    secondSemester: "2ème semestre",
    reportTypeModal_description: "Choisissez le type de tâche que vous souhaitez effectuer :",
    
    // Footer
    footerText: "Tous droits réservés &copy; 2025 - App de l'Inspecteur Pédagogique",
    
    // Add Teacher Modal
    addTeacherModal_addTitle: "Ajouter un Nouvel Enseignant",
    addTeacherModal_editTitle: "Modifier les Données de l'Enseignant",
    addTeacherModal_saveTeacher: "Ajouter l'Enseignant",
    addTeacherModal_saveChanges: "Enregistrer les Modifications",
    addTeacherModal_fillAllFields: "Veuillez remplir tous les champs obligatoires",
    addTeacherModal_selectFramework: "Choisir le Cadre",
    addTeacherModal_selectSubject: "Choisir la Matière",
    addTeacherModal_selectGrade: "Choisir le Grade",
    addTeacherModal_lastInspectionTitle: "Données de la dernière inspection",
    framework_primary: "Professeur de l'enseignement primaire",
    framework_middle: "Professeur de l'enseignement secondaire collégial",
    framework_high: "Professeur de l'enseignement secondaire qualifiant",
    reportCustomization_title: "Personnalisation",
    reportCustomization_fontFamily: "Police du rapport",
    reportCustomization_fontSize: "Taille de police",
    reportCustomization_logoScale: "Échelle du logo (%)",
    reportCustomization_margins: "Marges (cm)",
    reportCustomization_marginTop: "Haut",
    reportCustomization_marginBottom: "Bas",
    reportCustomization_marginSide: "Latérale",
    
    // Other Reports
    otherReports_pageTitle: "Autres rapports et correspondances",
    otherReports_formTitle: "Préparation d'un rapport ou correspondance",
    editReport: "Modifier le rapport",
    otherReports_documentNumber: "N° d'envoi:",
    otherReports_department: "À Monsieur/Madame",
    otherReports_selectDepartment: "Choisir le destinataire",
    otherReports_subject: "Objet",
    otherReports_subjectPlaceholder: "Objet du rapport ou de la correspondance...",
    otherReports_reference: "Référence",
    otherReports_referencePlaceholder: "Référence (optionnel)...",
    otherReports_addReference: "Ajouter une référence",
    otherReports_includeListInReport: "Inclure la liste dans le rapport",
    otherReports_autoSelectionShortcuts: "Raccourcis de sélection automatique (basés sur l'analyse des emplois du temps) :",
    otherReports_selectAllCleanSchedules: "Sélectionner tous les emplois du temps conformes",
    otherReports_selectSchedulesWithNotes: "Sélectionner les emplois du temps avec observations",
    allInstitutions: "Tous les établissements",
    allFrameworks: "Tous les cadres",
    activitySummary_inspectorTitle: "Bilan des activités de l'inspecteur pédagogique",
    otherReports_contentPlaceholder: "Écrivez les points essentiels ou un brouillon du contenu ici pour que l'IA puisse le reformuler...",
    otherReports_content: "Contenu",
    otherReports_invitedTeachersTitle: "Enseignants concernés / Invités",
    otherReports_searchTeacher: "Rechercher un enseignant...",
    otherReports_selectAll: "Tout sélectionner",
    saveChanges: "Enregistrer les modifications",
    otherReports_rephraseError: "Erreur de reformulation",
    view: "Aperçu",
    report_reference_field: "Réf:",
    report_from: "De Mr:",
    report_framework_label: "Cadre:",
    report_subject_label: "Spécialité:",
    report_to: "À:",
    report_subject_field: "Objet:",
    report_signature_line: "Salutations",
    otherReports_invitedListTitle: "Liste des Enseignants",
    otherReport_blankTemplate: "Rapport Vide",
    otherReport_selectTemplate: "Choisir un modèle",

    // Transmission Slip
    transmissionSlip_pageTitle: "Bordereau d'Envoi",
    academicYear: "Année Scolaire",
    allYears: "Toutes les années",
    allTypes: "Tous les types",
    transmissionSlip_createTitle: "Nouveau Bordereau d'Envoi",
    transmissionSlip_editTitle: "Modifier le Bordereau d'Envoi",
    slip_slipNumber: "N° d'envoi",
    transmissionSlip_slipNumberPlaceholder: "Ex: 12/2023",
    transmissionSlip_attachedReports: "Documents joints",
    transmissionSlip_noReportsAdded: "Aucun document ajouté",
    slip_item_copies: "Nbre de copies",
    slip_item_notes: "Observations",
    transmissionSlip_addActivities: "Ajouter des rapports de l'archive",
    transmissionSlip_savedSlips: "Bordereaux Enregistrés",
    transmissionSlip_noSavedSlips: "Aucun bordereau enregistré",
    transmissionSlip_fillAllFields: "Veuillez remplir tous les champs et choisir au moins un document",
    cancelEdit: "Annuler modification",
    selectActivities_title: "Choisir les documents à envoyer",
    selectActivities_add: "Ajouter ({0})",
    selectActivities_noReports: "Aucun rapport non envoyé",
    subject: "Objet",
    transmissionSlipModal_title: "Aperçu du Bordereau d'Envoi",
    slip_item_seq: "N°",
    slip_item_subject: "Type de document et objet",
    slip_activity_summary: "Bilan des activités",
    slip_notes_placeholder: "Notes groupées...",

    // Activity Summary
    activitySummary_pageTitle: "Bilan Annuel",
    activitySummary_reportType: "Type d'activité",
    activitySummary_allTypes: "Toutes les activités",
    activitySummary_searchPlaceholder: "Rechercher dans l'objet...",
    activitySummary_noReports: "Aucune activité enregistrée sur cette période.",
    activitySummary_type_visit: "Visites",
    activitySummary_type_inspection: "Inspections",
    activitySummary_type_other: "Autres activités",
    activitySummary_type_experimentalLessons: "Leçons expérimentales",
    activitySummary_type_seminars: "Séminaires et Rencontres Pédagogiques",
    activitySummary_type_trainings: "Formations",
    activitySummary_type_sharedWork: "Travail commun",
    activitySummary_type_tenure: "Titularisation et Aptitude",
    activitySummary_card_program_title: "Programmation",
    activitySummary_card_program_desc: "Planification et programmation des activités et des tâches",
    activitySummary_card_summary_title: "Bilan",
    activitySummary_card_summary_desc: "Affichage des statistiques et des rapports des activités réalisées",
    activitySummary_card_project_title: "Projet",
    activitySummary_card_project_desc: "Projet du programme de travail annuel",
    activitySummary_zipping_title: "Préparation des fichiers...",
    activitySummary_zipping_desc1: "La création du fichier ZIP pour tous les rapports de la saison est en cours.",
    activitySummary_zipping_desc2: "Veuillez patienter jusqu'à la fin de l'opération.",

    // Activity Summary Periods
    activitySummary_choosePeriod: "Choisir la période du bilan",
    activitySummary_semester: "Semestre",
    activitySummary_semester1: "1er Semestre",
    activitySummary_semester2: "2ème Semestre",
    activitySummary_annual: "Programme et Bilan",
    activitySummary_archiveTitle: "Archive des Saisons Scolaires",
    activitySummary_startDate: "Date de début",
    activitySummary_endDate: "Date de fin",
    activitySummary_showReports: "Afficher le bilan",
    activitySummary_changePeriod: "Changer la période / cycle",
    activitySummary_periodDateLabel: "Pour la période du {0} au {1}",

    // Inspection Space
    inspectionSpace_pedagogicalReports: "Rapports Pédagogiques",
    inspectionSpace_title: "Corps Enseignant",
    inspectionSpace_button: "Corps Enseignant",
    inspectionSpace_exit: "Sortie",
    inspectionSpace_chooseDay: "Choisir le jour",
    inspectionSpace_startTime: "Heure de début",
    inspectionSpace_duration: "Durée",
    inspectionSpace_morning: "Matin",
    inspectionSpace_afternoon: "Après-midi",
    inspectionSpace_hour: "Heure",
    inspectionSpace_hours: "Heures",
    inspectionSpace_status_busy: "En cours",
    inspectionSpace_status_free: "Libre",
    inspectionSpace_status_onLeave: "En congé",
    inspectionSpace_available: "Disponible",
    inspectionSpace_busy: "Occupé",

    // Teacher Schedule Modal
    scheduleModal_title: "Fiche d'Information",
    scheduleModal_tab_card: "Fiche Info",
    scheduleModal_tab_timetable: "Emploi du temps",
    scheduleModal_tab_licenses: "Sujet des Congés",
    scheduleModal_totalWeeklyHours: "Total des heures hebdomadaires:",
    scheduleModal_hour: "Heure",
    scheduleModal_violationsTitle: "Alertes sur les Normes Pédagogiques",
    scheduleModal_noViolations: "Aucune violation enregistrée.",
    scheduleModal_assignmentsTitle: "Liste des Séances Assignées",
    scheduleModal_noAssignments: "Aucune classe n'a été ajoutée à l'emploi du temps.",
    scheduleModal_scoreEvolution: "Évolution de la Note:",
    scheduleModal_academicYears: "Saisons Scolaires",
    scheduleModal_reportsHistory: "Historique des Rapports",
    scheduleModal_noReports: "Aucun rapport enregistré pour cet enseignant.",
    scheduleModal_scoreLabel: "Note:",
    violation_overTwoHours: "Séance dépassant deux heures",
    violation_lowWeeklyDuration: "Volume horaire hebdomadaire inférieur à 2h",
    violation_lowRestPeriod: "Repos inférieur à 44h",
    schedule_ass_label: "Association Sportive (ASS)",
    schedule_violation_label: "Alerte (Violation des règles)",
    evaluation_previousInspectionData: "Données de la dernière inspection",
    evaluation_errorProofreading: "Erreur lors de la correction linguistique",
    evaluation_noTextToProofread: "Aucun texte à corriger",
    evaluation_proofreadingAI: "Correction linguistique en cours...",
    evaluation_proofreadAIBtn: "Correction (AI)",
    evaluation_academicSeasons: "Saisons Scolaires",
    evaluation_criteria_prep: "Planification et préparation",
    evaluation_criteria_execution: "Gestion de la réalisation de la séance",
    evaluation_criteria_evaluation: "Évaluation",
    evaluation_criteria_professionalism: "Développement professionnel et engagement",
    evaluation_analyticalReport: "Rapport analytique",
    inspection_report_title: "Rapport d'inspection pédagogique",
    visit_report_title: "Rapport de visite de classe",
    grade_label: "Grade",
    observation_progress: "Observations sur le déroulement de la leçon",
    network_grid_c1: "Conditions matérielles et organisationnelles",
    network_grid_c1_i1: "État matériel de l'espace d'apprentissage",
    network_grid_c1_i2: "Moyens didactiques",
    network_grid_c1_i3: "Organisation de l'espace d'apprentissage",
    network_grid_c2: "Capacité d'organisation et de planification",
    network_grid_c2_i1: "Documents pédagogiques mis à jour",
    network_grid_c2_i2: "Respect du programme national d'enseignement",
    network_grid_c2_i3: "Réalisation de l'évaluation diagnostique",
    network_grid_c2_i4: "Clarté des objectifs tracés pour la leçon",
    network_grid_c2_i5: "Choix des moyens didactiques appropriés",
    network_grid_c2_i6: "Respect de l'enveloppe horaire de la séance/du cycle",
    network_grid_c2_i7: "Adoption du projet pédagogique, sportif et de cycle",
    network_grid_c3: "Réalisation des travaux liés à la fonction",
    network_grid_c3_i1: "Maîtrise des concepts et terminologie de la matière",
    network_grid_c3_i2: "Maîtrise de la méthodologie d'enseignement",
    network_grid_c3_i3: "Cohérence de la leçon (progression et harmonie)",
    network_grid_c3_i4: "Respect de la répartition du temps",
    network_grid_c3_i5: "Utilisation des moyens didactiques",
    network_grid_c3_i6: "Prise en compte des différences individuelles",
    network_grid_c3_i7: "Adéquation de l'évaluation/soutien aux objectifs",
    network_grid_c4: "Recherche et innovation",
    network_grid_c4_i1: "Adoption de nouvelles méthodes innovantes",
    network_grid_c4_i2: "Utilisation des TICE et ressources numériques",
    network_grid_c4_i3: "Activités de recherche pédagogique",
    network_grid_c5: "Rendement",
    network_grid_c5_i1: "Engagement et participation des apprenants",
    network_grid_c5_i2: "Activité des apprenants (interaction/créativité)",
    network_grid_c5_i3: "Résultats des évaluations",
    network_grid_c5_i4: "Contribution aux activités du sport scolaire",
    network_grid_c6: "Comportement professionnel",
    network_grid_c6_i1: "Communication professionnelle institutionnelle",
    network_grid_c6_i2: "Présence et tenue (Charisme)",
    network_grid_c6_i3: "Aspect relationnel avec les apprenants",
    network_level_0: "Non évalué",
    network_level_1: "À travailler",
    network_level_2: "Satisfaisant",
    network_level_3: "Bien",

    // Statistics
    statistics_pageTitle: "Tableau de Bord des Statistiques",
    statistics_visits: "Visites",
    statistics_inspections: "Inspections",
    statistics_other: "Autres rapports",
    statistics_total: "Total Général",
    statistics_chartTitle: "Évolution des activités par mois",
    statistics_distributionTitle: "Répartition des activités",

    // Educational Research
    research_pageTitle: "Recherche Pédagogique",
    research_labelTopic: "Sujet de recherche proposé :",
    research_placeholderTopic: "Entrer le sujet de recherche...",
    research_generateButton: "Générer la proposition méthodologique",
    research_generating: "Préparation du guide...",
    research_section_problem: "Problématique proposée",
    research_section_hypothesis: "Hypothèses",
    research_section_methodology: "Méthodologie et outils",
    research_section_plan: "Plan de recherche proposé",
    research_helpText: "Cette fenêtre vous aide à construire une structure initiale pour la recherche pédagogique.",
    research_btn_instruments: "Générer des modèles d'outils et de grilles",
    research_btn_refineMethodology: "Affiner la méthodologie",
    research_btn_fullFormulation: "Formulation complète et détaillée",
    research_section_fullFormulation: "Formulation complète et détaillée du travail",
    research_downloadText: "Télécharger le texte",
    research_filename_prefix: "recherche_",
    research_title_refineMethodology: "Générer des détails plus précis sur la méthodologie et les outils",
    research_title_fullFormulation: "Rédiger l'intégralité du travail de recherche en détail",
    research_title_instruments: "Générer des modèles pratiques d'outils",

    // Days
    day_monday: "Lundi",
    day_tuesday: "Mardi",
    day_wednesday: "Mercredi",
    day_thursday: "Jeudi",
    day_friday: "Vendredi",
    day_saturday: "Samedi",
    day_sunday: "Dimanche",
    
    // About Modal
    aboutModal_title: "À propos de l'Application",
    aboutModal_philosophyTitle: "Philosophie de l'Application",
    aboutModal_howToUseTitle: "Comment utiliser l'application",
    aboutModal_philosophy_p1: "L'application 'L'Inspecteur' est une plateforme numérique intégrée spécialement conçue pour répondre aux besoins professionnels précis des inspecteurs d'éducation physique et sportive. Ce projet naît de la nécessité de moderniser la pratique professionnelle et de dépasser les méthodes traditionnelles de gestion administrative et pédagogique, permettant à l'inspecteur de se concentrer davantage sur les aspects d'encadrement et pédagogiques.",
    aboutModal_philosophy_p2: "L'application vise une numérisation complète du parcours d'inspection, de l'archivage intelligent des dossiers des enseignants, en passant par la rédaction automatisée des rapports assistée par l'intelligence artificielle, jusqu'à la gestion précise des correspondances et la génération du bilan annuel en un seul clic, tout en garantissant la sécurité et la confidentialité des données via un stockage local et cloud crypté.",
    aboutModal_featuresTitle: "Caractéristiques et Fonctions Principales",
    aboutModal_feature1_title: "Gestion Intelligente",
    aboutModal_feature1_desc: "Une base de données centrale permettant de suivre le parcours professionnel de chaque enseignant (grade, échelon, date de recrutement...) avec la possibilité d'importer des listes depuis des fichiers Excel et de classer les enseignants par établissements et secteurs (public/privé).",
    aboutModal_feature2_title: "Rédaction Assistée",
    aboutModal_feature2_desc: "Une interface flexible pour la rédaction des rapports d'inspection et de visites de classe, soutenue par un moteur d'intelligence artificielle pour formuler les observations pédagogiques de manière professionnelle. Le système prend en charge l'exportation des documents aux formats Word et PDF prêts à imprimer avec l'en-tête officielle.",
    aboutModal_feature3_title: "Espace d'Inspection",
    aboutModal_feature3_desc: "Un tableau de bord interactif offrant une vision globale de la carte éducative, où il est possible de suivre les emplois du temps des enseignants, leur situation administrative, et d'identifier ceux disponibles pour une visite ou une inspection en temps réel.",
    aboutModal_feature4_title: "Suivi Administratif",
    aboutModal_feature4_desc: "Une bibliothèque de modèles prêts à l'emploi pour les correspondances administratives, les rapports de séminaires et les rencontres pédagogiques. Il comprend également un système de création de bordereaux d'envoi pour contrôler et suivre le mouvement des documents sortants.",
    aboutModal_feature5_title: "Bilan et Statistiques",
    aboutModal_feature5_desc: "Génération automatique et complète du bilan des activités (premier semestre, deuxième semestre, annuel) avec des graphiques illustrant l'évolution des performances. Le système inclut une archive organisée par saisons scolaires pour un accès facile aux données précédentes.",
    aboutModal_step1_title: "1. Configuration du Profil et des Données de Base :",
    aboutModal_step1_desc: "Commencez par ajuster vos données professionnelles sur la page 'Inspecteur', puis construisez la base de données des enseignants soit manuellement, soit via la fonction d'importation rapide depuis un fichier Excel pour gagner du temps.",
    aboutModal_step2_title: "2. Exécution des Tâches Sur le Terrain et Pédagogiques :",
    aboutModal_step2_desc: "Utilisez les boutons rapides de l'interface principale pour documenter des visites ou des inspections. Vous pouvez exploiter l'intelligence artificielle pour améliorer la formulation des observations et garantir la qualité du rapport.",
    aboutModal_step3_title: "3. Sauvegarde, Archivage et Exportation Numérique :",
    aboutModal_step3_desc_A: "Tous vos mouvements sont automatiquement sauvegardés dans la mémoire de l'appareil pour assurer le travail hors ligne.",
    aboutModal_step3_desc_B: "Vous pouvez à tout moment prévisualiser les documents, les exporter dans des formats professionnels (Word/PDF) ou les partager directement via des médias numériques.",
    aboutModal_step4_title: "4. Sécurité et Sauvegarde Régulière :",
    aboutModal_step4_desc: "Assurez-vous de sauvegarder régulièrement vos données à partir des paramètres. Vous pouvez également activer la synchronisation cloud pour garantir un accès à vos données depuis n'importe quel appareil en toute sécurité.",
    aboutModal_closing: "Cette application a été développée comme une contribution technique pour améliorer le système d'inspection éducative",

    // Sport Activities and Categories (Translations for dynamic content)
    "الارجاع الكروي": "Jeux de Renvoi",
    "الرقابة والتحرر": "Marquage/Démarquage",
    "الكره الطائرة": "Volley-ball",
    "كرة الريشة": "Badminton",
    "التنس": "Tennis",
    
    // Levels
    "الأولى إعدادي": "1ère Année Collège",
    "الثانية إعدادي": "2ème Année Collège",
    "الثالثة إعدادي": "3ème Année Collège",
    "الجذع مشترك": "Tronc Commun",
    "الأولى بكالوريا": "1ère Année Baccalauréat",
    "الثانية بكالوريا": "2ème Année Baccalauréat",

    // Departments / Services (Destinataires)
    "مصلحة الشؤون التربوية والتخطيط والخريطة المدرسية": "Service des affaires pédagogiques, de la planification et de la carte scolaire",
    "مصلحة الموارد البشرية والشؤون الإدارية والمالية": "Service des ressources humaines et des affaires administratives et financières",
    "المركز الاقليمي للامتحانات": "Centre Provincial des Examens",
    "المركز الإقليمي للامتحانات": "Centre Provincial des Examens",
    "المركز الاقليمي للإمتحانات": "Centre Provincial des Examens",
    "المركز الإقليمي للإمتحانات": "Centre Provincial des Examens",
    "المركز الاقليمى للامتحانات": "Centre Provincial des Examens",
    "المركز الإقليمى للامتحانات": "Centre Provincial des Examens",
    "المركز الاقليمى للإمتحانات": "Centre Provincial des Examens",
    "المركز الإقليمى للإمتحانات": "Centre Provincial des Examens",
    "مصلحة تأطير المؤسسات التعليمية والتوجيه": "Service de l'encadrement des établissements scolaires et de l'orientation",
    "مصلحة الشؤون القانونية والشراكة والتواصل": "Service des affaires juridiques, du partenariat et de la communication",

    deliveredStatus: "Livré",
    setAsDelivered: "Marquer comme livré",
    cancelDelivery: "Annuler la livraison",
    deliverAll: "Tout marquer comme livré",
    clonedAsNew: "Copier comme nouveau",
    noSavedReports: "Aucun rapport enregistré.",
    archive: "Archive",
    otherReports_displayTeachersList: "Afficher la liste des enseignants",
    otherReports_displayInstitutionsOnly: "Afficher uniquement les établissements",


    // Specific Activities
    "التربية البدنية": "Éducation Physique",
    "الرياضة": "Sport",
    "نصف الطويل": "Demi-fond",
    "القفز الطولي": "Saut en longueur",
    "القفز العلوي": "Saut en hauteur",
    "الجري السريع": "Course de vitesse",
    "الجري الطويل": "Course de fond",
    "مدرج ضمن جدول الحصص": "Inscrit à l'emploi du temps",
    "غير مدرج": "Non inscrit",
    "رمي القرص": "Lancer du disque",
    "رمي الرمح": "Lancer du javelot",
    "الجري بالتناوب": "Course de relais",
    "حركات أرضية": "Gymnastique au sol",
    "حصان القفز": "Saut de cheval",
    "المتوازي": "Barres parallèles",
    lang_all: "Tous",
    lang_fr_btn: "Français",
    lang_ar_btn: "العربية",
    filter_language: "Filtrer par langue",
    calendar_next: "Suivant",
    calendar_previous: "Précédent",
    calendar_today: "Aujourd'hui",
    calendar_month: "Mois",
    calendar_week: "Semaine",
    calendar_day: "Jour",
    calendar_agenda: "Agenda",
    calendar_date: "Date",
    calendar_time: "Heure",
    calendar_event: "Événement",
    calendar_no_events: "Aucun événement dans cette période.",
    event_completed: "Terminé",
    event_add_new: "Ajouter un nouvel événement",
    event_day_title: "Événements du",
    event_edit_title: "Modifier l'événement",
    event_add_title: "Ajouter un événement",
    event_title_label: "Titre de l'événement",
    event_title_placeholder: "Ex: Visite d'inspection, séminaire pédagogique...",
    event_location_label: "Lieu",
    event_location_placeholder: "Ex: École Ibn Khaldoun, Salle 4...",
    event_from_label: "De",
    event_to_label: "À",
    event_importance_label: "Importance",
    event_importance_low: "Normale (Bleu)",
    event_importance_medium: "Moyenne (Orange)",
    event_importance_high: "Haute (Rouge)",
    event_completed_task: "Tâche terminée",
    event_zoom_hint: "Cliquez sur l'aperçu pour zoomer/dézoomer",
    notification_settings_title: "Paramètres des notifications locales",
    notification_no_events: "Aucune activité programmée. Veuillez d'abord ajouter des activités.",
    notification_description: "Deux notifications seront envoyées pour chaque activité à venir. Définissez l'heure ci-dessous :",
    notification_test_btn: "Envoyer une notification de test",
    notification_schedule_btn: "Programmer les notifications",
    notification_scheduled: "Notifications programmées avec succès",
    notification_error_not_supported: "Les notifications ne sont pas supportées par ce navigateur",
    notification_error_denied: "Permission de notification refusée",
    notification_error_failed: "Échec de la programmation des notifications",
    month_january: "Janvier",
    month_february: "Février",
    month_march: "Mars",
    month_april: "Avril",
    month_may: "Mai",
    month_june: "Juin",
    month_july: "Juillet",
    month_august: "Août",
    month_september: "Septembre",
    month_october: "Octobre",
    month_november: "Novembre",
    month_december: "Décembre",
    annual_program: "Programme Annuel",
    annual_project: "Projet de programme de travail annuel",
    enable_notifications: "Activer les notifications locales",
    export_calendar: "Exporter vers le calendrier",
    digital_summary: "Bilan Numérique",
    preview_print_summary: "Aperçu et impression du bilan",
    notification_first: "Première notification",
    notification_second: "Seconde notification",
    notification_reminder_before: "Rappel avant :",
    notification_browser_note: "Note : Vous utilisez la version navigateur. Les notifications programmées ne fonctionnent de manière fiable que sur l'application mobile (Android/iOS).",
    time_weeks: "Semaines",
    time_days: "Jours",
    time_hours: "Heures",
  }
};
